### ISSUE TITLE
DxDataGrid: ability to Hide/Disable Columns in Display/Edit template 

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#10]
Hi, 

Is there a way to hide/disable certain columns in the display/edit template of DxDataGrid? In particular the primary key(s) columns of the dataitem.

thx

**Comment by SergeySeleznyov** [comment]
Hi,
 
Currently, we do not have an option to hide a column from editing. We will implement in the future.
However, you can fully customize it using **EditFormTemplate**.
Please, take a look at the [demo](https://demos.devexpress.com/blazor/GridEditFormTemplateValidation).
 
Perform the following steps:
- Create columns only for the fields you would like to display.
- In Edit Form Template, create a form with fields you would like to edit.
 
Please let me now if this approach is helpful.
Thanks!

**Comment by SergeySeleznyov** [comment]
@goldmannyc,
 
Our webinar about the Blazor is going to start soon:
https://www.devexpress.com/support/webinars/
Would be great to see you there.
