### ISSUE TITLE
DxTreeView ExpandNode in LoadOnDemand mode

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#100]
Hi support team,

this is kind of a question or howto.
When using `LoadChildNodesOnDemand=true` on the `DxTreeView` the method `ExpandToNode` does not correctly expand child nodes. This is explainable because the children are currently not loaded. How could it be possible to load the children anyway?

Thanks

**Comment by sven5** [comment]
Update: I found a solution calling `SetNodeExpanded` multiple times  from parent to child. However, this is kind of flickering. I wonder what's the "official" solution. 😄

**Comment by zabelin-vladimir** [comment]
Hello @sven5

> This is explainable because the children are currently not loaded.

You are absolutely right. We will update our documentation which is related to the mentioned API (*LoadChildNodesOnDemand* and *ExpandToNode*) to describe this situation.
At the moment, we don't provide any specific API to expand DxTreeView to the specific node if the *LoadChildNodesOnDemand* property is enabled. Your approach with expanding nodes one-by-one using the *SetNodeExpanded* node seems to be an appropriate in the case if you know the whole path to the necessary node.

**Comment by sven5** [comment]
Thank you @zabelin-vladimir 
It's always a pleasure to work with you guys. 😄
