### ISSUE TITLE
NullReferenceException in DxFormLayout when DxFormLayoutItem Field is another class

### ISSUE THREAD

**Issue by CodedBeard** [DevExpress/Blazor#101]
I initially thought this was a repeat of #11, however, I've now discovered it only happens when attempting to access a property of the Data that is another class. This is using version 19.2.4, and only seems to be an issue with DxFormLayout, as other controls like DxDataGrid work fine with the same data structure.

This throws:
```csharp
<DxFormLayout Data="@Test">
    <DxFormLayoutItem Field="@nameof(TestClass.Id)" Caption="Reference:" ColSpanMd="8" />
    <DxFormLayoutItem Field="@nameof(TestClass.BusinessDetails.CompanyName)" Caption="Company Name:" ColSpanMd="8" />
</DxFormLayout>

@code {
    public class TestClass
    {
        public int Id { get; set; } = 900;
        public BusinessDetailsTest BusinessDetails { get; set; } = new BusinessDetailsTest();
    }

    public class BusinessDetailsTest
    {
        public string CompanyName { get; set; } = "Testing";
    }

    public TestClass Test = new TestClass() { BusinessDetails = new BusinessDetailsTest() { CompanyName = "Test" } };

}
```
This doesn't:
```csharp
<DxFormLayout Data="@Test">
    <DxFormLayoutItem Field="@nameof(TestClass.Id)" Caption="Reference:" ColSpanMd="8" />
</DxFormLayout>

@code {
    public class TestClass
    {
        public int Id { get; set; } = 900;
        public BusinessDetailsTest BusinessDetails { get; set; } = new BusinessDetailsTest();
    }

    public class BusinessDetailsTest
    {
        public string CompanyName { get; set; } = "Testing";
    }

    public TestClass Test = new TestClass() { BusinessDetails = new BusinessDetailsTest() { CompanyName = "Test" } };

}
```

**Comment by outsidergiant** [comment]
Hi,

The @nameof(TestClass.BusinessDetails.CompanyName) expression will return "CompanyName", see the following thread:
https://stackoverflow.com/questions/27898178/why-does-nameof-return-only-last-name

I would expect modifying the code in the following manner:
```
@{ var CompanyName = $"{nameof(TestClass.BusinessDetails)}.{nameof(BusinessDetailsTest.CompanyName)}"; }


<DxFormLayout Data="@Test">
    <DxFormLayoutItem Field="@nameof(TestClass.Id)" Caption="Reference:" ColSpanMd="8" />
    <DxFormLayoutItem Field="@nameof(CompanyName)" Caption="Company Name:" ColSpanMd="8" />
</DxFormLayout>
```
However, an exception is still thrown in this case, so I need additional time to research it. I'll reply to you once I have any news.

**Comment by CodedBeard** [comment]
Hi,

I had wrongly assumed it was some sort of overloaded usage for nameof (on reflection no idea why). I've also gone back and looked at the DxDataGrid and realised that while it was not throwing, it was also failing to map the data properly. Switching the grid to use a hardcoded field name string does load correctly, but then like you, I found it still throws in the DxFormLayout with a hardcoded field name.

**Comment by zabelin-vladimir** [comment]
Hello @CodedBeard 

We will continue to work on this issue in the context of the [FormLayout for Blazor - NullReferenceException is thrown if its item is bound to the complex property](https://www.devexpress.com/Support/Center/Question/Details/T868480/formlayout-for-blazor-nullreferenceexception-is-thrown-if-its-item-is-bound-to-the) ticket. You can create an account on our site and add this ticket to Favorites to get a notification when we update that.

**Comment by CodedBeard** [comment]
DevExpress support have now updated the ticket to state this has been fixed in the next release. Thanks
