### ISSUE TITLE
Feature request: Conditional selection of nodes in DxTreeView

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#103]
Hi support team,

while working with your DxTreeView I came across a limitation.
When setting `AllowSelectNodes` to true the expand-on-click functionality no longer works. One has to explicitly click on the chevron symbol. I got customer feedback that's kind of odd especially on mobile devices. 
It would be great to limit selection only to leave nodes. We're using the tree to select products - and when the user clicks on a product leaf some additional info is loaded and the product should keep selection. 

**Proposed solutions:**
- I could imagine to have an enum for `NodeSelectionMode`, with value `None`, `All`, `LeavesOnly`
- Another way would be to extend the `ITreeViewNodeInfo` with a new property `AllowSelection` to allow conditionally selection of nodes. 

Thanks

**Comment by zabelin-vladimir** [comment]
Hello @sven5

If the main issue in your scenario is that you cannot expand a node by a click (if the `AllowSelectNodes` property is enabled), I recommend you set the `NodeExpandCollapseAction` property to the `TreeViewNodeExpandCollapseAction.NodeClick` value. Please try this approach and let me know if it helps

If you want to prevent selection of certain nodes, please clarify your requirements. I look forward to your reply.

**Comment by sven5** [comment]
@zabelin-vladimir 
Thanks! That's exactly what I wanted. I'm fine with that.
