### ISSUE TITLE
Question: DxTextBox submit on Enter on mobile device

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#104]
Hi DevEx Team,

I'm struggling with a strange behavior of DxTextBox on mobile device.
I'd like to implement a search textbox that auto-submits on enter key press.
My code looks like:
`<DxTextBox ClearButtonDisplayMode="@DataEditorClearButtonDisplayMode.Auto"
                               NullText="Enter keyword..." type="search" aria-label="Search" @bind-Text="@SearchTerm"
                               @onkeyup="@(e => RunSearch(e))" />`
```csharp
@code {
    string keyCode;
    string SearchTerm { get; set; }

    void RunSearch(KeyboardEventArgs e)
    {
        if (e.Code == "Enter")
        {
            if (!string.IsNullOrWhiteSpace(SearchTerm))
            {
                NavigationManager.NavigateTo($"/search/{SearchTerm}");
            }
        }
    }
}
```

It works on desktop but not on my Android device. The keyup event seems not to fire.
Could you get it working?

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

The *onkeyup* is not a part of [DevExpress TextBox's public API](https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxTextBox._members). This is the default Blazor event. Would you please check the same behavior with the <input> tag instead of DxTextBox and let me know your results?

**Comment by sven5** [comment]
Hi @zabelin-vladimir 
There was an error in the `KeyboardEventArgs` - it seems on Android mobiles the `Code` property is always empty.
However, when using the `Key` property it works ok.
