### ISSUE TITLE
[request] BladeView component

### ISSUE THREAD

**Issue by wstaelens** [DevExpress/Blazor#106]
BladeView as a new UI component would be very useful!

https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.ui.controls.bladeview

**Comment by zabelin-vladimir** [comment]
Hello @wstaelens

I forwarded your request to our Blazor team and we will discuss the possibility of implementing such a component. However, I cannot provide you with any time frames.

**Comment by wstaelens** [comment]
Looking forward to it!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
