### ISSUE TITLE
HTML Attributes for DxTextBox Input Elements

### ISSUE THREAD

**Issue by 314159265meow** [DevExpress/Blazor#107]
Hello, is it possible to set arbitrary HTML attributes for the `input` Elements of a `DxTextBox`?

Right now we have the problem that we want to set `autocomplete="off"` for one of our Input Fields. 
If we set the attribute directly to the `DxTextBox` or use the `Attributes` collection, then the attribute is put on the containing `div` instead of the `input` element.

Same problem with the `maxlength` attribute.

Regards,
Michael

**Comment by outsidergiant** [comment]
Hello Michael,

Thank you for contacting us.

Currently, attributes are assigned to the root element. We will discuss the idea of providing a mechanism for adding attributes directly to input elements of the editors.

At this moment, you can do the same via [JSInterop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1). Mark the required editor with a custom CSS class by setting its **CssClass** property and select an input element contained inside an element with this CSS class. After this, you can assign the required attributes. Let me know if you have additional questions.

**Comment by zabelin-vladimir** [comment]
Hello Michael,

We implemented the [HTML Attributes](https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxTextBox#html-attributes) feature with the [20.1.4](https://community.devexpress.com/blogs/aspnet/archive/2020/06/09/blazor-ui-components-official-release-with-new-controls-amp-features-and-blazor-reports-available-in-v20-1.aspx) version of our components. 
Please check this feature on your side and share your thoughts with me. Your feedback is really appreciated.

**Comment by 314159265meow** [comment]
Hi, took me some time to come back to these features. The update did exactly what we needed and works great so far. Thanks for implementing it 👍
