### ISSUE TITLE
Renderfragment for DxComboBox

### ISSUE THREAD

**Issue by olowk** [DevExpress/Blazor#108]
Would it be possible to have a RenderFragment for the DxComboBox for the items so that we can display images (from a database) and text together?

**Comment by zabelin-vladimir** [comment]
Hello @olowk 

As far as I understand, you want to implement something similar to the [Item template](https://demos.devexpress.com/ASPxEditorsDemos/ASPxComboBox/ItemTemplate.aspx) feature in our ComboBox for ASP.NET WebForms. Am I right? 
We have this feature in our ToDo list.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
