### ISSUE TITLE
DxComboBox bound to an enum doesn't display initial selected value

### ISSUE THREAD

**Issue by olowk** [DevExpress/Blazor#109]
When DxCombobox is bound to an enum [Data=@((IEnumerable<EnumType>)Enum.GetValues(typeof(EnumType)))] then it won't display the initial selected value that is bound to [@bind-SelectedItem="@SelectedEnumType"]

**Comment by zabelin-vladimir** [comment]
Hello @olowk 

I created a sample project based on your code and it works properly on my side. Would you please modify my sample to reproduce this issue? 

[GHI109.zip](https://github.com/DevExpress/Blazor/files/4409961/GHI109.zip)

**Comment by olowk** [comment]
Hello,

In your demo project it works indeed, but it doesn't in my project. I have also devexpress 19.2.4 and I checked if there are javascript errors, but none happen. Here is a screenshot of what I see of my combobox with an enum:
[cid:bd7925e1-f217-4d8f-ae87-8012d1059f90]

I understand that you can't do much if you can't simulate it, so I'll try to search more why it doesn't work on my side. If I find something, or I can simulate it in a small project I'll let you know.

With kind regards,
Omer Loose
________________________________

**Comment by zabelin-vladimir** [comment]
Hi Omer @olowk 

I'm looking forward to your results. Don't hesitate to contact me if you reproduce that with a sample project which you can share with me.

**Comment by devritter** [comment]
Hello,
I found out that the initial value is only working if the int-value of your initial enum value is not equal to zero. so as a little temporary "fix", you can explicitly define the integer values of your enum starting by 1.

**Comment by zabelin-vladimir** [comment]
Hello @devritter 

Thank you for your clarification, I understood how to reproduce this issue. It seems that we have resolved it in the context of [this ticket](https://supportcenter.devexpress.com/ticket/details/t880330/combobox-for-blazor-the-null-text-is-shown-on-editing-the-grid-with-a-default-enum-value). So, I recommend you wait for the official 19.2.5 release and check this scenario after updating our component.
