### ISSUE TITLE
NullReferenceException in DxFormLayout

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#11]
Hi,

When using plain DxFormLayoutItem I get the following error:

```
[2019-06-06T11:33:48.166Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at DevExpress.Blazor.Internal.ValueEditingTemplateHelper.GetNumberValueEditor(Object value, Action`1 onValueChanged, Boolean sureValueIsNumberic)
   at DevExpress.Blazor.Internal.ValueEditingTemplateHelper.GetValueEditor(Object value, Action`1 onValueChanged)
   at DevExpress.Blazor.FormLayout.Internal.FormLayoutLevelRenderer.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()

```

markup:
`<DxFormLayoutItem Field="@nameof(Model.UserName)" Caption="Login-Name *" ColSpanMd="6" />`

Workaround is to use full Template:
```
<DxFormLayoutItem Caption="Login-Name *" ColSpanMd="6">
     <Template>
            <DxTextBox bind-Text=@Model.UserName></DxTextBox>
      </Template>
</DxFormLayoutItem>
```

Seems that there is an issue in `GetValueEditor` - because it tries to call `GetNumberValueEditor` - however the propety UserName in my case is a string and not a number.

Regards
Sven 

PS: keep up the good work. :smirk:

**Comment by SergeySeleznyov** [comment]
Hi @sven5,
 
Thank your for posting the report to us!
 
I have reproduced the issue in the following example:
 
```
@page "/FormLayout"
 
<DxFormLayout Data=@Model>
    <DxFormLayoutItem Field="@nameof(Model.UserName)" Caption="Login-Name *" ColSpanMd="6" />
</DxFormLayout>
 
@functions {
    public class ModelType {
        public string UserName => "My Name";
    }
    ModelType Model = null; // NullReferenceException in "GetNumberValueEditor"
    //ModelType Model = new ModelType(); // Works fine
}
 
```
 
Would you please check that you have the same scenario, so we can be sure that we are working exactly on the issue you ran into.
 
If it is the same scenario, please check if you want to bind to the null Model.

Thank you for your warm words! :)

**Comment by sven5** [comment]
Hi @SergeyAlexeev 

Thanks for your time to create a small sample.
At first you're right, when the Model is null the error is thrown. That's kind of normal Blazor behavior.
However I already assured that my Model never is null. 

The problem also occurs when the Model's properties are null - not the Model itself. Please see my modified code below:

```
@page "/FormLayout"

<DxFormLayout Data=@Model>
    <DxFormLayoutItem Field="@nameof(Model.UserName)" Caption="Login-Name *" ColSpanMd="6" />
</DxFormLayout>

@functions {
    public class ModelType
    {
        public string UserName => null;
    }
    //ModelType Model = null; // NullReferenceException in "GetNumberValueEditor"
    ModelType Model = new ModelType(); // Works fine
}
```

Regards
Sven

**Comment by SergeySeleznyov** [comment]
I've reproduced the issue, and I agree with you: this scenario is common and thus should work.
 
Thank you very much for helping us to make the product better!

**Comment by CodeKarno** [comment]
Hi @sven5! 

We have created a report in our official [Support Center](https://www.devexpress.com/Support/Center/Question/List/1) and will update it once we have any news. Keep an eye on it or create a DevExpress account and add this thread to Favorites to get notifications: [DxFormLayout - NullReferenceException occurs when the component is bound to Model with null properties](https://www.devexpress.com/Support/Center/Question/Details/T747618/dxformlayout-nullreferenceexception-occurs-when-the-component-is-bound-to-model-with)

**Comment by SergeySeleznyov** [comment]
@sven5,
 
I'm happy to inform that I've found the solution.
The fix will be in the next release.
 
By the way, our webinar about the Blazor is going to start soon:
https://www.devexpress.com/support/webinars/
Would be great to see you there.

**Comment by sven5** [comment]
@SergeySeleznyov 

Thanks for your update. I'm sure you will fix it - as always :smile:

Yes I already joined the webinar. :smiley:

We're already developing some Intranet applications with server-side Blazor since several months. We are looking forward to the evolution of the DevExpress Blazor library. I already included some DxEditors and DxDataGrids in our applications. 

Regards
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5,
 
We have just updated a NuGet package to the 0.0.9 version.
It contains a fix to the issue you have described here.
 
Would you please check whether your project operates properly now?
 
Thank you!

**Comment by SergeySeleznyov** [comment]
I'm closing this issue. Please feel free to reopen it should you run into any difficulty with the fix provided.
 
Thank you @sven5  !

**Comment by sven5** [comment]
Hi @SergeySeleznyov 

I can confirm it's working now.

Thanks
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5 

Awesome! Thank you!
