### ISSUE TITLE
DxDateEdit (ScrollPicker) - Scrolling moves opposite direction than expected

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#110]
When using the DxDateEdit in ScrollPicker mode on desktop, the scrolling behavior moves opposite to what the system scroll direction is. So when I scroll down, the list moves up.

I know this is how scrolling works on MacOS, but for windows users, this is quite jarring and takes a bit of getting used to.

Is there a setting to change the direction that the list scrolls?

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen 

Thank you for your feedback. Our DateEdit doesn't provide such property at the moment. We will discuss the possibility to implement it in the future versions.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
