### ISSUE TITLE
update Blazor WebAssembly 3.2.0 Preview 4

### ISSUE THREAD

**Issue by geffzhang** [DevExpress/Blazor#111]
A new preview update of Blazor WebAssembly is now available!  

Debugging in Visual Studio and Visual Studio Code
Auto-rebuild in Visual Studio
Configuration
New HttpClient extension methods for JSON handling

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/

**Comment by zabelin-vladimir** [comment]
Hello @geffzhang 

Thank you for sharing this information with us. We plan to support this version of Blazor WebAssembly in our next update. 

Regards,
Vova

**Comment by geffzhang** [comment]
Recently released?

**Comment by geffzhang** [comment]
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/

**Comment by zabelin-vladimir** [comment]
Hello @geffzhang 

We have released the 19.2.5-Preview NuGet package, [which](https://github.com/DevExpress/Blazor/blob/master/changelog.md#1925-preview) supports .NET Core 3.1.3 and Blazor Web Assembly 3.2.0 Preview 4 updates. You can install this package from the NuGet package manager if the *Include prerelease* checkbox is enabled.
