### ISSUE TITLE
DxDataGrid - MultiSelection selects text as well

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#113]
When selecting with shift+click, the text gets selected as well

Demo gif from blazor demo site:
![demo](https://user-images.githubusercontent.com/29714139/78999687-28f89500-7b19-11ea-94b7-4440a0de8cd8.gif)

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen

Thank you for your report. We are aware of this issue and have a task on our ToDo list to resolve it.

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen 

We are going to address technical requests only in our Support Center.
So, I recommend you add the following thread to your Favorites to get a notification when we update it: [Blazor Data Grid - Browser selection appears when the Shift key is held during the multi-row selection](https://supportcenter.devexpress.com/ticket/details/t895505/blazor-data-grid-browser-selection-appears-when-the-shift-key-is-holt-during-multi-row)

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
