### ISSUE TITLE
DxDataGrid -> column property path

### ISSUE THREAD

**Issue by olowk** [DevExpress/Blazor#114]
Is it possible to support a property path in the field of DxDataGridColumn?
Like the property path 'TradePartner.Name'?

Now it's not possible to sort (or show) such columns which means that you can't show complex data in virtualization mode without first mapping the whole data list to a simple type.

**Comment by zabelin-vladimir** [comment]
Hello @olowk 

As far as I understand, you want to bind a column in DxDataGrid to some complex property. If so, I recommend you check the [DataGrid for Blazor - Bind to complex properties](https://supportcenter.devexpress.com/ticket/details/t847125/datagrid-for-blazor-bind-to-complex-properties) ticket where we discussed a similar scenario. Does the suggested approach meet your requirements?

**Comment by olowk** [comment]
Hello,

Yes that's exatly what I mean.
I'll try the suggestion tomorrow, but I'm sure it will work. I totally forgot that nameof(Cikk.GyartoId.Nev) only returns the name of the last property (Nev).

Sorry about the double post and thanks very much for the fast response!

With kind regards,
Omer


________________________________

**Comment by zabelin-vladimir** [comment]
You are welcome, Omer!
