### ISSUE TITLE
Charts/Grid don't resize well

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#117]
Charts and grids have to be unusually large in order to not have scroll bars appear. Any way to change the scaling, or maybe a stretch to fit property?
![Annotation 2020-04-27 074321](https://user-images.githubusercontent.com/29714139/80368612-fe1d7900-885a-11ea-8769-06f4e2c66c67.png)

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen 

Usually, the size of our controls is calculated based on their content's size. Would you please provide me with a runnable sample project illustrating the problematic cases, so that I can check it on my side? I need to research it locally to provide you with any suggestions.

**Comment by GerritBergen** [comment]
Sorry for late reply. The behavior I would expect (at least for the chart) is that it scales based on the parents width/height. A use case would be that I want a smaller chart that doesn't take up so much room.

In the screenshot provided above, you'll see I have two points on the line chart, but yet the chart still shows 0.8, 0.4, 0.2, etc and the height between each line is quite large. The chart shown is using 390.53px x 369.8px (using inspect element), and that's just rather large for a desktop screen, ya know?

**Comment by GerritBergen** [comment]
Maybe something like this?

![demo](https://user-images.githubusercontent.com/29714139/81594401-d49e3a80-938e-11ea-831f-15fc9f39bc0b.gif)

This was made using the inspect element tool and the setting up the [svg viewbox](https://stackoverflow.com/a/19485375/7723172):

In the example the chart is just following the aspect ratio, but it would be really cool if it resized both, its width and height.

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen

Thank you for your clarification. At the moment, our DxChart doesn't support changing its size according to its container. We will discuss the possibility to support such a scenario in future releases. Thank you for your feedback!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
