### ISSUE TITLE
Issue with Firefox 60.8.0

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#118]
Hi DevExpress team.

I got some customer feedback the the `DxComboBox` does not work with Firefox Quantum 60.8.0esr (32bit). 
I couldn't find this version in the downloads so I wasn't able to verify it.
Maybe you have some other testing possibilities and find out what could lead to this issue.
I'm also unsure if this browser is a valid platform for Blazor.

Thanks
Sven

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

As far as I Understand from [this article](https://www.ghacks.net/2019/08/12/goodbye-firefox-quantum-hello-firefox-browser/), *Firefox Quantum* is the name of previous versions of *Firefox Browser*. I checked our ComboBox demos with the latest version of the Firefox browser and didn't reproduce any issues. Is it possible to ask your customer to update his Firefox version to the latest one and check the reported issue once again?

**Comment by sven5** [comment]
Hi @zabelin-vladimir 

I agree with the latest version of _Firefox_ there are no issues. I will ask them to update to a more recent version.
Thanks
