### ISSUE TITLE
DxComboBox dropdown list position

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/Blazor#119]
Is there any way to control the dropdown window position ? If the comboxbox is near the bottom of the screen, it's chopped off the screen. Ideally, depending on the height of the dropdown window and the space remaining, the dropdown window should appear above the control instead of below (like a regular input select works)

**Comment by zabelin-vladimir** [comment]
Hello @drinkwater99

We plan to implement such a feature for all our editors which have a drop-down element. It should be implemented in the next release.

**Comment by drinkwater99** [comment]
Is there any temporary workaround ?

Also, when is the next release planned ?

**Comment by zabelin-vladimir** [comment]
At the moment, there is no available workaround. We expect the next release to be launched in a few weeks.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
