### ISSUE TITLE
[Suggestion] DxDataGrid - Column picker

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#120]
It would be really cool if the user could pick what columns to show/hide and having it save in the layout string.

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen 

The column chooser feature was implemented in the latest 19.2.5-preview version. Enable the "Include prerelease" check box in the NuGet Package manager to install this version. You can use the following code to show the corresponding UI element:

`<DxDataGrid ... >`
`    <HeaderTemplate>`
`        <DxToolbar ItemSize="ToolbarItemSize.Small">`
`            <DxDataGridColumnChooserToolbarItem Alignment="ToolbarItemAlignment.Right" />`
`        </DxToolbar>`
`    </HeaderTemplate>`
`    <Columns>`
`        ...`
`    </Columns>`
`</DxDataGrid>`
