### ISSUE TITLE
[Suggestion] DxDataGrid - Adaptibility

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#121]
Showing/hiding columns based on screen size.

[Similar to this](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/GridAdaptabilityOverview/jQuery/Light/)

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen

Thank you for your suggestion. We have the corresponding task regarding the adaptive/responsive layout in our ToDo list. However, I cannot provide you with an exact time frame when it will be implemented.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
