### ISSUE TITLE
[Suggestion] DxDataGrid - Saving expanded groups

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#122]
Saving expanded groups in the layout string so when a user returns to the grid, he doesn't have to re-expand what he had open.

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen

Thank you for your suggestion. The main bottleneck in this scenario is the fact that we should store keys of the expanded rows as string values. However, it's a correct scenario where your key field has some other type than string.
We will discuss this feature in the future.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
