### ISSUE TITLE
Virtual Scrolling Grid Multiselection

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#123]
Hi

When you select a row in a grid with paging, it deselects all other rows on the page but not on other pages. That makes sense for me.
In the Virtual Scrolling Grid I think of the whole grid as one big (virtual) page. So anywhere I click, all the other elements get deselected. But thats not the case. If I select one row, then scroll down until a new block of elements is loaded and select again, two elements are selected.

Is this expected behaviour for you or will this be changed?

**Comment by zabelin-vladimir** [comment]
Hello @rysep2

> In the Virtual Scrolling Grid I think of the whole grid as one big (virtual) page.

No, in [Virtual Scrolling mode](https://demos.devexpress.com/Blazor/GridPagingAndScrolling#VirtualScrolling), our DataGrid loads data by pages on scrolling. Because of that, the described behavior is expected.
