### ISSUE TITLE
DxDataGrid - refresh not update/repaint all grid

### ISSUE THREAD

**Issue by andreadottor** [DevExpress/Blazor#124]
Hi,
I try to use the DxDataGrid (19.2.5-preview) with different data sources, es IEnumerable\<TypeA\> and after I change to IEnumerable\<TypeB\> (TypeA e TypeB not have the same properties).
This is the code:
```
<DxDataGrid @ref="@_gridRef"
       Data="@Descriptor.DataSource"
       @bind-SingleSelectedDataRow="@SelectedItem"
       PageSize="10"
       ShowFilterRow="true">
        @foreach (System.Data.DataColumn col in Descriptor.GetColumns())
            {
                switch (col.DataType.FullName)
                {
                    case "System.Int32":
                    <DxDataGridSpinEditColumn Field="@col.ToString()" Caption="@col.ColumnName" />
                        break;
                    case "System.DateTime":
                    <DxDataGridDateEditColumn Field="@col.ToString()" Caption="@col.ColumnName" DisplayFormatString="D" EditFormatString="d" />
                        break;
                    case "System.String":
                    <DxDataGridColumn Field="@col.ToString()" Caption="@col.ColumnName" />
                        break;
                }
            }
</DxDataGrid>
```

If I call StateHasChanged (or the Refresh method of _gridRef), the rows data change correctly, but the grid keeps the same number of columns, and not update the headers text.

**Comment by outsidergiant** [comment]
Hi,

Thank you for contacting us. We are aware of this issue and working on it in the context of the following thread:
[DataGrid for Blazor - Column captions cannot be dynamically updated](https://supportcenter.devexpress.com/ticket/details/t873077/datagrid-for-blazor-column-captions-cannot-be-dynamically-updated). Add it to Favorites to be notified once its status changes.
