### ISSUE TITLE
AddDevExpressBlazor in Startup not Program

### ISSUE THREAD

**Issue by Mark-Phillipson** [DevExpress/Blazor#125]
At the following link:

[https://github.com/DevExpress/Blazor#create-a-new-project](https://github.com/DevExpress/Blazor#create-a-new-project)

Paragraph 7.2

The documentation is misleading, it suggests adding the DevExpress Blazor service in the Program Class.

Whereas other documentation states it should be in the Startup  Class.

**Comment by outsidergiant** [comment]
Hello Mark,

Do you use the Blazor WebAssembly? If so, then the AddDevExpressBlazor should be added in the Program.cs file. In our documentation this information matches the one you found at [https://github.com/DevExpress/Blazor#create-a-new-project](https://github.com/DevExpress/Blazor#create-a-new-project). Please review the following paragraph of our Getting Started help topic:
[Step 3 - Register DevExpress Resources](https://docs.devexpress.com/Blazor/401057/getting-started/create-a-new-application#step-3---register-devexpress-resources).
Let me know if you have additional questions.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
