### ISSUE TITLE
DxDataGrid - bad resize when VerticalScrollBarMode is set and menu is hide

### ISSUE THREAD

**Issue by PrzemekPB** [DevExpress/Blazor#126]
Like in subject:

![GridError](https://user-images.githubusercontent.com/9599903/82424216-20369f80-9a85-11ea-9352-455ca8379974.png)

**Comment by GerritBergen** [comment]
Having the same problem. Added this to my stylesheet as a workaround for now:

`.dxbs-gridview > .card > div {
    width: 100% !important;
}`

**Comment by outsidergiant** [comment]
Hi.

Thank you for contacting us. We are aware of this issue and fixed it in the context of the following thread:
[DataGrid for Blazor - The grid's layout is not adjusted after changing a grid's width if a horizontal scrollbar is enabled](https://supportcenter.devexpress.com/ticket/details/t878575/datagrid-for-blazor-the-grid-s-layout-is-not-adjusted-after-changing-a-grid-s-width-if-a), so the fix will be applied in the upcoming update.
