### ISSUE TITLE
Blazor WebAssembly 3.2.0 Support

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#127]
Just wondering when official support for [the latest version](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-now-available/) is planned for release?

**Comment by outsidergiant** [comment]
Hello Gerrit,

Thank you for your interest. We are working on this. Stay tuned for our updates.

**Comment by smithgor** [comment]
Hi, Any update on this?  Would be good to get a rough idea on release date as I'm looking to get started using it on a new project.  Many thanks.

**Comment by outsidergiant** [comment]
Hello,

If everything goes according to plan, we will to ship a new version with new controls and features including Blazor WebAssembly 3.2.0 support in the first half of June.

Thanks.

**Comment by smithgor** [comment]
Thanks - helps me plan accordingly.
