### ISSUE TITLE
DxComboBox dropdown width

### ISSUE THREAD

**Issue by dwbeva** [DevExpress/Blazor#129]
Is there a way to specify the width of the drop-down window? When using in virtual list mode, the width of the drop-down window changes depending on the width of the items which appear making it very difficult to effectively scroll down the list using the scroll bar.

**Comment by zabelin-vladimir** [comment]
Hello @dwbeva

DxComboBox doesn't provide the corresponding property to change the width of its dropdown element.
So, at present, it is only possible to specify the dropdown width using your own CSS rule. The CSS selector should be the following: ".dxbs-dm.dropdown-menu.dxbs-listbox"

**Comment by zabelin-vladimir** [comment]
Hello,

We have recently released [*v20.1.5*](https://github.com/DevExpress/Blazor/releases/tag/20.1.5) of our Blazor components. The corresponding NuGet package is already available.  
We implemented the [DropDownWidthMode](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxComboBoxBase-1.DropDownWidthMode) properties for our DxComboBox component. Please try to use it in your scenario without the mentioned workaround to accomplish this task. Let me know if it helps.
