### ISSUE TITLE
Lookup; Combobox; search multiple columns

### ISSUE THREAD

**Issue by BlagoCuljak** [DevExpress/Blazor#13]
Hi again,
I'm having task where user need to select one Item from Lookup/Combobox, but, the table Item has a ItemName and ItemCode, both of which should display in Lookup, and both columns to be searchable. I have done this easily in WPF, but don't see any example in Blazor.

Is that covered in any scenario?

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,

This is the **Combo Box / Multiple column support** feature from our [RoadMap](https://community.devexpress.com/blogs/aspnet/archive/2019/06/24/blazor-roadmap-what-you-can-expect-in-the-next-few-months-from-devexpress.aspx). 

Until we release this feature, there is a workaround: you can implement a new property for the data item type, where you can compose a text representation of any property you need. So, Combo Box will work with this new property only and will show this property value in the list.

Please note that the Combo Box search is the **Combo Box / Filtering support** feature from the [RoadMap](https://community.devexpress.com/blogs/aspnet/archive/2019/06/24/blazor-roadmap-what-you-can-expect-in-the-next-few-months-from-devexpress.aspx). It will be released very soon (within several days). It looks like as follows:

![image](https://user-images.githubusercontent.com/950357/60167734-55eaee00-980c-11e9-920d-244a10eb9ca8.png)

So, if you implement the workaround, you will get the working search through the new property too.

Would you please let us know whether the suggested workaround is suitable to you?

**Comment by BlagoCuljak** [comment]
Well, I will not use workaround, rather try new feature in new Blazor release and also help you to test it out. :-)

I can wait couple of days/weeks even.

**Comment by SergeySeleznyov** [comment]
Thank you @BlagoCuljak for helping us to make our product better!
 
We will think about virtual scrolling inside Combo Box to operate will long lists.

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,

We have just updated the demos and components (NuGet package).
You can find the Combo Box with a filter in the "Combo Box - Incremental Filtering" [demo](https://demos.devexpress.com/blazor/ComboBox).

The "Combo Box - Business Object List as Data Source" demo shows how to work with several fields:

```
public string Text => $"{FirstName} {LastName} ({Department} Dept.)";
```
 
We will continue working on our components' enhancements. Thank you for your feedback and interest!

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,
 
I hope with new features you can now achieve your goal in your project.
I'm closing this issue. Please feel free to reopen it (or create a new one) should you have any difficulty.

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,

We have just released new version.
Add virtual scrolling to the [Data Grid](https://demos.devexpress.com/blazor/GridVirtualScrolling) and [ComboBox](https://demos.devexpress.com/blazor/ComboBox). (Addressing your request about "50,000 items." in the ComboBox.)

Would you please take a look at it? Whether it meets your requirements?

Thank you very much for your time and feedback!

**Comment by BlagoCuljak** [comment]
Well, I'm having issues upgrading to preview 6, from preview 5. Hopefully I in next couple days should get back on track.

Preuzmite Outlook za Android<https://aka.ms/ghei36>

________________________________

**Comment by BlagoCuljak** [comment]
Hi @SergeySeleznyov , this upgrade rocks, works smooth with huge amount of data.

Do you plan to have any special type of search, eg. search inside of string by keywords.

Eg. Item Name, is "Milka chocolate with nuts 150g". At the moment I can search keyword "Milka" and returns hunderts of results. I would like to narrow my search by using multiple keywords, like "+Milka +150 +nuts" so it returns just one item.

I have used terific WPF grid, and this search rocked.

https://documentation.devexpress.com/WPF/11402/Controls-and-Libraries/Data-Grid/Filtering-and-Searching/Search

**Comment by SergeySeleznyov** [comment]
Hi @BlagoCuljak ,,
 
Happy to hear that you like our new feature!
 
We'll definitely support the capability to search by several keywords.
This task is already in our back log.
 
Thank you very much for staying with us.
 
P.S. Yesterday we released Blazor preview 7.
A new update will be ready shortly.

**Comment by BlagoCuljak** [comment]
@SergeySeleznyov great to hear that, and Microsoft commits that Preview 7 will supported in production. Just in time.

Sorry open up all these feature requests in same thread, it was easier. :)

**Comment by SergeySeleznyov** [comment]
@BlagoCuljak, you are always welcome to open any number of feature requests.
Hope other people open theirs, and we will be able to discuss their scenarios.
This greatly helps us prioritize our task list.
 
Thank you!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
