### ISSUE TITLE
Reset grid sorting

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#131]
Hi

I want the user to have a button to reset his custom grid sort and change back to the default sort. My first thought was to use this:
`GridRef.LoadLayout("{\"ColumnSortingStates\":null}")
`
But using the LoadLayout method on the grid reference doesn't seem to work.

I know there is a OnLayoutRestoring event where you can set LoadLayout on the IDataGridLayout object. Does that mean i have to force an update of the grid, so that the OnLayoutRestoring event is called and i can change the sorting? Isn't there a cleaner way?

**Comment by zabelin-vladimir** [comment]
Hello @rysep2

Our DxDataGrid doesn't have any API to set/reset sorting for the specific columns. I need more time to discuss this issue with our team. I hope we can find an appropriate workaround.

**Comment by zabelin-vladimir** [comment]
Hello @rysep2

We have resolved several issues related to the Save/Restore Layout feature in the latest release. I checked your idea with *v20.1.6* and it seems to be possible to clear the grid sorting state using the *LayoutRestoring* event. We have also discussed the same scenario in the following thread: [T924800](https://supportcenter.devexpress.com/ticket/details/t924800/disappearing-column-filters-on-grid-after-refresh). Please check my sample in the answer. In your case, I recommend you use the following code:

```
    void OnLayoutRestoring(IDataGridLayout dataGridLayout) {
        var layout = ulManager.GetCurrentLayout();

        if (!string.IsNullOrEmpty(layout)) {
            var obj = (Newtonsoft.Json.Linq.JObject)Newtonsoft.Json.JsonConvert.DeserializeObject(layout);
            obj.Property("ColumnSortingStates").Remove();
            dataGridLayout.LoadLayout(obj.ToString());
        }
    }
```
