### ISSUE TITLE
[Question/Enhancement] DxSchedulerDataStorage AppointmentsSource design

### ISSUE THREAD

**Issue by eaton-sam** [DevExpress/Blazor#132]
The DxScheduler DataStorage class requires a AppointmentsSource as an IEnumerable to bind against the scheduler. Do we have to provide an enumerable of all appointments from DateTime.Min to DateTime.Max? As far as I can tell there is no way to bind data for the current viewed date range. 

It would be nice if we could either have events that trigger on navigate, so that we can bind new data for the date range in view, or better yet if we could implement our own DxSchedulerDataStorage class.

The DxSchedulerDataStorage has functions for getting appointments in a range:
`public IEnumerable<DxSchedulerAppointmentItem> GetAppointments(DxSchedulerDateTimeRange interval);`

However currently none of the functions in DxSchedulerDataStorage are overridable.
An interface, IDxSchedulerDataStorage, that we could implement to provide our own data storage would be great.

As it is this component isn't really usable. I can't pull all appointment data from a service or database in case a user navigates to any given date, just to show the next 3 days.

Thanks

**Comment by andrew-bird** [comment]
Hello @eaton-sam ,
Thank you for such a detailed description. You are right, DxScheduler and DxSchedulerDataStorage work with a full collection of appointments. At the moment, we don't have an appropriate event to notify about changing the visible interval and to load appointments for this interval.

We will continue to improve our components. I forwarded your ideas to our Blazor team. Thank you for your feedback!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
