### ISSUE TITLE
DxDataGrid change default css class 

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#135]
Hi DevExpress team,

default table HTML:
`<table class="dxbs-table table-bordered table-sm">`

the DxDataGrid defaults to "table-sm". How to remove this default value? I'd like to have a more mobile friendly table with increased padding of rows. Or let's say how to change RowHeight of the DxDataGrid?

Thanks

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

You can set the *CssClass* property of your grid and create some specific CSS rule to implement this task:
```
<style>
    .MyGrid table td,th {
        padding: .75rem!important;
    }
</style>
<DxDataGrid Data="@forecasts" CssClass="MyGrid">
    <DxDataGridColumn Field="Summary"></DxDataGridColumn>
    <DxDataGridDateEditColumn Field="Date"></DxDataGridDateEditColumn>
</DxDataGrid>
```
Please check this approach and let me know if it helps.

**Comment by sven5** [comment]
Thanks @zabelin-vladimir for this workaround.
However, I already found another way to change the padding, I'm attaching to the `HtmlDataCellDecoration` event in the following way:

```
    void OnHtmlDataCellDecoration(DataGridHtmlDataCellDecorationEventArgs<Model.ShelfDetail> eventArgs)
    {
        eventArgs.CssClass = " p-2";
    }
```
While `p-2` is standard bootstrap 4 helper class. 

What I'd like you to keep in mind that there should be a simple way to change the default `table-sm` styling. For instance there could be an Enum that changes the table layout, like `TableSmall`, `TableBig`, `TableNormal`.

**Comment by zabelin-vladimir** [comment]
Hello @sven5

Yes, your approach seems to be great. Thank you for sharing it with me.
We will discuss the possibility of implementing such a property for the whole DataGrid component. Your feedback is appreciated!
