### ISSUE TITLE
DxCombobox memory leak

### ISSUE THREAD

**Issue by troepolik** [DevExpress/Blazor#136]
We have a problem with DxCombobox memory leak in server side blazor app
There is some static List of JsInteropProxy that hold reference to combobox components
And then it some how hold RemoteRender (it is some class from blazor)
This is my example:
```
<DxComboBox @ref="ComboBox"
                    Data="@InternalList"
                    FilteringMode="DataGridFilteringMode.StartsWith"
                    TextFieldName="Name"
                    TextChanged="@OnTextChanged"
                    SelectedItem="@InternalValue"
                    SelectedItemChanged="@OnSelectionChanged" />
```
I tried to add ref to that component by @ref="ComboBox"
and then I tried to dispose him , but it had no effect
```
public void Dispose()
    {
        InternalList = null;
        if(ComboBox!= null)
        {
            ComboBox.TextChanged = null;
            ComboBox.SelectedItemChanged = null;
            ((IDisposable)ComboBox).Dispose();
        }
    }
```
In profiler I processed Force GC a few times before get snapshot :
![image](https://user-images.githubusercontent.com/11777855/84290489-65ae3000-ab4c-11ea-8335-159fad55d172.png)
Can I clear this list as workaround? By reflection or somehow else?

**Comment by zabelin-vladimir** [comment]
Hello @troepolik 

Thank you for your report. We reproduced this behavior. We will research it in the context of the [ComboBox for Blazor - The memory leak is detected in the server-side Blazor application](https://supportcenter.devexpress.com/ticket/details/t898747/combobox-for-blazor-the-memory-leak-is-detected-in-the-server-side-blazor-application) ticket. We will update this GitHub issue when this issue is resolved.

**Comment by troepolik** [comment]
Hi @zabelin-vladimir , thank you for reply, can you give us any workaround for a first time?
Can I clear this list by myself?

**Comment by zabelin-vladimir** [comment]
Hello @troepolik

At the moment we cannot offer any appropriate workaround for this issue. I recommend you wait for the official fix to address this situation.

Regards,
Vova
