### ISSUE TITLE
DxDataGrid sort by invisible column

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#137]
Hi DevEx team,

I'd like to sort my DxDataGrid data by a column that shouldn't be visible. 
I already tried the following ways but neither works

1. Sort IQueryable DataSource, sorting does not apply
2. Add Column but set it to Visible = false, column is hidden but the grid isn't sorted
3. Set column's width to 0% still shows the column

Thanks for your support.

**Comment by zabelin-vladimir** [comment]
Hello @sven5

It seems that your second way works properly on my side. I tested it with the *20.1.4* version of our Blazor components and the following code:
```
<DxDataGrid Data="temp">
    <DxDataGridColumn Field="ID"></DxDataGridColumn>
    <DxDataGridColumn Field="Name"></DxDataGridColumn>
    <DxDataGridColumn Field="Group" SortIndex="0" SortOrder="DataGridColumnSortOrder.Descending" Visible="false"></DxDataGridColumn>
</DxDataGrid>

@code {
    List<TestModel> temp = new List<TestModel>();
    protected override void OnInitialized() {
        temp.Add(new TestModel() { ID = 0, Name = "John", Group = 2 });
        temp.Add(new TestModel() { ID = 1, Name = "Robert", Group = 1 });
        temp.Add(new TestModel() { ID = 2, Name = "Adam", Group = 2 });
        temp.Add(new TestModel() { ID = 3, Name = "James", Group = 0 });
        base.OnInitialized();
    }
    public class TestModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Group { get; set; }
    }
}
```
The result is the following:
![image](https://user-images.githubusercontent.com/42369178/84393260-0dd30000-ac04-11ea-9937-6496283cf064.png)

Would you please modify my code to illustrate this behavior or provide me with a sample project demonstrating it? I look forward to your reply.

Regards,
Vova

**Comment by sven5** [comment]
Thanks @zabelin-vladimir 

After updating to 20.1.4 this is working now.
