### ISSUE TITLE
DxDataGridColumnChooserToolbarItem causing exception in Blazor WebAssembly app

### ISSUE THREAD

**Issue by emilyztc** [DevExpress/Blazor#138]
I've added a DxDataGridColumnChooserToolbarItem to my Blazor WebAssembly app.  I can click and open the column chooser without issue.  However, when I close the column chooser popup by clicking away elsewhere in the application, the following exception occurs:

Unhandled exception rendering component: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
      TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
          at Module.b (https://localhost:44348/_content/DevExpress.Blazor/modules/esm-columnchooser-610be8f0.js:1:988)

This error does NOT occur when I click the X button to close the column chooser popup.  It only occurs when I click away elsewhere in the application.  Also, this error does not occur if I use a DxDataGridColumnChooserToolbarItem in a Blazor Server App.

Example code:
```
@page "/"

<DxDataGrid Data="@DataSource" ShowFilterRow="false" CssClass="mw-1100">
    <HeaderTemplate>
        <DxToolbar>
            <DxDataGridColumnChooserToolbarItem Alignment="ToolbarItemAlignment.Right" />
        </DxToolbar>
    </HeaderTemplate>
    <Columns>
        <DxDataGridColumn Field="@nameof(Employee.FirstName)" />
    </Columns>
</DxDataGrid>

@code {
    List<Employee> DataSource = new List<Employee>();

    public class Employee
    {
        public string FirstName { get; set; }
    }
}

```

**Comment by imtrobin** [comment]
I have the same problem.

**Comment by outsidergiant** [comment]
Hello Robin,

Thank you for contacting us. We are working on this issue in the context of the following report:
[DataGrid for Blazor - Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'](https://supportcenter.devexpress.com/ticket/details/t899355/blazor-dxdatagrid-failed-to-execute-getcomputedstyle)
We will update it once we have any news.
