### ISSUE TITLE
DxDataGrid disable/hide columns in New/Edit/Update 

### ISSUE THREAD

**Issue by imtrobin** [DevExpress/Blazor#140]
Hi,

There are some columns which should be read only or hidden when doing New/Edit/Update. Is that doable now? I saw a post asking for this a year ago.

https://github.com/DevExpress/Blazor/issues/10

**Comment by outsidergiant** [comment]
Hi,

DataGrid columns have the [EditorVisible](https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxDataGridColumn.EditorVisible) property which specifies whether a column editor is visible in the grid when a user edits grid data.

**Comment by cubed-it** [comment]
I also find the current solution suboptimal.
1) it would be good if you could show fields disabled, so you don't lose the context
2) it would be useful to be able to specify directly whether a field may only be changed when it is created, or also when it is edited
