### ISSUE TITLE
[Request] Scheduler - Month/Year view

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#141]

**Comment by andrew-bird** [comment]
Hello @GerritBergen 

Thank you for your request. I forwarded it to the team. We will discuss the implementation of the Month/Year view for the DxScheduler component. However, I cannot give you any time frames.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
