### ISSUE TITLE
DxDataGrid Footer Summaries

### ISSUE THREAD

**Issue by Bogdan0205** [DevExpress/Blazor#142]
Hello,
Is there any intention to add the summaries footer like [this ](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/GridSummaries/Angular/Light/)one  that's already implemented for javascript libraries?

**Comment by zabelin-vladimir** [comment]
Hello @Bogdan0205

At this moment, our DxDataGrid doesn't support the group/total summary feature.
This feature is in our plans. Stay tuned to our updates.

**Comment by Bogdan0205** [comment]
Thanks for the reply. 
In the meantime I've also encontered another scenario. When enabling the filters row, I'd like to be able to disable the filter for certain columns. Is this also on your roadmap?

**Comment by zabelin-vladimir** [comment]
Yes, we are working on an API which allows you to hide the editor in the filter row for specific column.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
