### ISSUE TITLE
Where is DevExpress.Blazor.Reporting?

### ISSUE THREAD

**Issue by jimnkey** [DevExpress/Blazor#144]
Trying to test drive components using free license... reporting was key.  
Any chance that might be made available or am I not pointing to the correct nuget endpoint(s)?
Or maybe the namespace changed -- no longer `DevExpress.XtraReports`?

Thanks.

**Comment by zabelin-vladimir** [comment]
Hello @jimnkey 

Though [DevExpress Reports](https://www.devexpress.com/subscriptions/reporting/) supports Blazor, it is not included in our Blazor component distribution. To use DevExpress Reports within your Blazor application/project, you must purchase a DevExpress Subscription (Reporting Subscription, ASP.NET Subscription, DXperience, or Universal).
You can start the 30-days trial period to check if our Reporting Tools meets your requirements: [Trial .NET Core Controls Via NuGet](https://docs.devexpress.com/GeneralInformation/120534/installation/install-devexpress-controls-using-nuget-packages/net-core-controls-via-nuget)

**Comment by XinMaAT** [comment]
try to run the BlazorDemo.ServerSide with reference of BlazorDemo.Reporting. It does not work as the demo site, do i need to something else ,except add the project reference. (by the way i have installed DevExpress.Blazor.Reporting, compile just fine! )

when i click Reports-> Document Viewer, i got this error

>  System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=BlazorDemo
  StackTrace:
   at BlazorDemo.Shared.DemoScriptLoader.<InvokeAsync>d__21`1.MoveNext() in C:\Users\ma.x\Documents\codecpu\Blazor\demo\BlazorDemo.ServerSide\BlazorDemo\Shared\DemoScriptLoader.cs:line 23

**Comment by zabelin-vladimir** [comment]
Hello @XinMaAT

Please do the following and let me know if it helps:

* Open the "demo\BlazorDemo.ServerSide\BlazorDemo.ServerSide\appsettings.ini" file;
* Change the value of the *hostingStartupAssemblies* property to the following: "BlazorDemo;BlazorDemo.Reporting";
* Open the *BlazorDemo.ServerSide* solution and add a reference of *BlazorDemo.Reporting* to the *BlazorDemo.ServerSide* project


After these steps, you should open the corresponding demo reporting pages without any errors.

**Comment by XinMaAT** [comment]
> 
> 
> Hello @XinMaAT
> 
> Please do the following and let me know if it helps:
> 
>     * Open the "demo\BlazorDemo.ServerSide\BlazorDemo.ServerSide\appsettings.ini" file;
> 
>     * Change the value of the _hostingStartupAssemblies_ property to the following: "BlazorDemo;BlazorDemo.Reporting";
> 
>     * Open the _BlazorDemo.ServerSide_ solution and add a reference of _BlazorDemo.Reporting_ to the _BlazorDemo.ServerSide_ project
> 
> 
> After these steps, you should open the corresponding demo reporting pages without any errors.

@zabelin-vladimir  thanks a lot, it works now!
