### ISSUE TITLE
Dx Scheduler background cell color

### ISSUE THREAD

**Issue by dwbeva** [DevExpress/Blazor#145]
Is there any way to set the background color of specific date time cells? For example, I would like to set on a specific date the cells from 9am to 5am in light green (to indicate availability in my specific use case).

**Comment by andrew-bird** [comment]
Hello @dwbeva 

At the moment, our DxScheduler doesn't have any API to customize time cells. We will discuss the possibility of implementing such a scenario in future releases. Thank you for your feedback!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
