### ISSUE TITLE
DocumentMetadata : dynamic meta data

### ISSUE THREAD

**Issue by vd3d** [DevExpress/Blazor#147]
Hi,

First, thanks for the DocumentMetadata component ;-)

But, imagine I have a generic web page, let's say Post.razor , this one is a user post... but each post will be different.

So, I wish to generate a different title, tags, etc... par post. Is it possible ?

Today, everything is based on a list and not generated on the fly after navigation ?

**Comment by zabelin-vladimir** [comment]
Hello @vd3d

I'm not sure that I understand your scenario properly. The *DocumentMetadataComponent* component is added on the *_Host.cshtml* page, which is an entry point of the whole Blazor application. Would you please clarify if you want to have several pages in your case? I would appreciate it if you describe your scenario in greater detail. I look forward to your reply.

**Comment by zabelin-vladimir** [comment]
Hello @vd3d

We didn't get any reply regarding this question. We are going to address technical requests only in our Support Center.
So, if you still need our assistance with this question, please create a new ticket in our [Support Center](https://www.devexpress.com/ask) and clarify your scenario in greater detail.
We will be happy to help you with this and any other questions regarding our product!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
