### ISSUE TITLE
DxDataGrid pagination through API?

### ISSUE THREAD

**Issue by MitchZinck** [DevExpress/Blazor#148]
Hi,

I am currently pulling results from my api into the DxDataGrid but some sets of data are humongous. Our api supports pagination so I was wondering if it is possible to retrieve data based on incrementing page number in the DataGrid?

I.E. going from page 2 to page 3 would create an api call which requests page 3 data results, and then refresh the DxDataGrid to display the data.

**Comment by zabelin-vladimir** [comment]
Hello @MitchZinck 

Our DxDataGrid supports the [CustomData](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxDataGridBase-1.CustomData) property, which can be used in this scenario. Please check this property and let me know if it helps.
