### ISSUE TITLE
[Request] DxGrid - Column filter customization

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#149]
Custom filters for specific columns. (eg. A column that's used as a mailing address, and the user wants to filter by state/country/etc)

Here's how I could see it working:
Instead of showing a text field and typing something in, it would be a button that when clicked, would show a popup window that has a template that can be filled with whatever. It would be up to us to save whatever settings we decide to show in that window.
When the filter is run (like on data load, or when the "Apply" button is pressed in the popup window), it calls an event that we can subscribe to, and change visibility of rows based on our settings.

This would be such an awesome feature to have. Any chance you guys can implement it? :)

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen 

We plan to improve the filtering feature in our DxDataGrid in future. As far as I understand from your task, you need some template for the filter row editor and the corresponding API to apply filter. We will discuss these features in the context of filter feature enhancement. 
Thank you for your feedback!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
