### ISSUE TITLE
Nice NEW Demo

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/Blazor#15]
Looks great team!
Just sent the link  to friends

So, in this demo, you're using the new TreeView as your menu system, than the old Blazor accordion?
This allows multi layer indention for sub menus.

**Comment by SergeySeleznyov** [comment]
Thank you @BenHayat !
 
Using TreeView also reduces the navigation height.
We are trying avoid internal page scrolls (navigation scroll) as much as we can.
