### ISSUE TITLE
Css not being generated on some dev machines

### ISSUE THREAD

**Issue by BlagoCuljak** [DevExpress/Blazor#150]
Hi, I have a made with Devexpress 20.1.4, and everything was good. The code is on git server, and I have laptop and computer that I work with.

On my computer, everything works fine. However, when I pull that same code to my laptop, then DX css/js is not generated. I don't know how you produce this css.

This is missing on laptop:
[https://prnt.sc/tcnbfr](https://prnt.sc/tcnbfr)

**Comment by BlagoCuljak** [comment]
Sorry about this, this was fixed by using
`webBuilder.UseStaticWebAssets();`

In Program.cs

**Comment by zabelin-vladimir** [comment]
Hello @BlagoCuljak

I'm happy to hear that you found an appropriate solution. We described this issue in the following part of our troubleshooting article: [Failed to load resource](https://docs.devexpress.com/Blazor/401608/common-concepts/troubleshooting#failed-to-load-resource).
