### ISSUE TITLE
DxPopup centered position

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/Blazor#151]
Is there any way to have the popup displayed centered (horizontally and vertically) on the screen ?

**Comment by zabelin-vladimir** [comment]
Hello @drinkwater99

Our DxPopup component doesn't have any API to accomplish this task at the moment. However, the DxPopup control is rendered as native HMTL elements, thus it is possible to use standard approaches to specify its position and size. Please refer to the following ticket where we discussed a similar task and use recommendations from that thread as a starting point: [Popup for Blazor - How to change a popup's size and position](https://supportcenter.devexpress.com/ticket/details/t833027/popup-for-blazor-how-to-change-a-popup-s-size-and-position).

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
