### ISSUE TITLE
Huge list to Grid - fetch on scroll/filter

### ISSUE THREAD

**Issue by BlagoCuljak** [DevExpress/Blazor#152]
I have a big list of Items, like 100,000 items. It takes a quite a lot time to load entire list.

We do use Virtual Scroll, but it seems that is only used to render items. Is there any chance we can load some top x of items and if there scrolling/filtering send some parameters to fetch next x items.

[Like this.](https://docs.devexpress.com/WPF/120193/controls-and-libraries/data-grid/binding-to-data/binding-to-any-data-source-with-virtual-sources/virtual-sources-overview)

**Comment by zabelin-vladimir** [comment]
Hello @BlagoCuljak

I recommend you bind your grid using the [CustomData](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxDataGridBase-1.CustomData) property. In this case, you can load only a part of data based on the current grid state.
