### ISSUE TITLE
[Request] Edit text on DxDataGridColumnChooserToolbarItem

### ISSUE THREAD

**Issue by andreadottor** [DevExpress/Blazor#158]
There is no property for change the button text in the DxDataGridColumnChooserToolbarItem component.

**Comment by outsidergiant** [comment]
Hi,

Thank you for your feedback. I've shared it with the team and we will consider such an API while planning new features. But I cannot give you any time frame.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
