### ISSUE TITLE
Latest Github demo, issue

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/Blazor#16]
Hello team;

The Gitub demo source seem to have some codes from preview 10 and not 11, for example the NavMenu.razor is from the old one preview.

https://github.com/DevExpress/Blazor/blob/master/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/Pages/NavMenu.razor

Hope this helps.
..Ben

**Comment by SergeySeleznyov** [comment]
Hello @BenHayat  ,
 
Thank you for bringing this to our attention.
The NavMenu.razor file that has an effect is in the "Shared" directory. I have deleted this file from the "Pages" directory.
 
Thank you very much!
