### ISSUE TITLE
[Question] DateTime control

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#160]
Just curious when the date & time control is releasing

Thanks :)

**Comment by outsidergiant** [comment]
Hello Gerrit,

We plan to ship more controls and features for Blazor. Please refer to our recent roadmap for the next major release (v20.2):
[Blazor - Roadmap 2020 (Mid-Year Update)](https://community.devexpress.com/blogs/aspnet/archive/2020/07/09/blazor-roadmap-2020-mid-year-update.aspx)
The feature you are asking about, the Time Section of our DateEdit component, is part of our 2020 roadmap. To prevent false promises and misleading, I cannot give you any precise ETA. Please stay tuned to our blogs and newsletters for more information.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
