### ISSUE TITLE
Usage guide for DxDataGrid DataAsync method along with EF Core

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#162]
Hi @zabelin-vladimir 

I would be looking forward if you could create an example or write some documentation about best practices when connecting real world data from database through EF core to `DxDataGrid`.
Especially when using the `DataAsync` method there are some caveats one has to understand.

The problem is that `DxDataGrid` seems a little limited while it only accepts a `Task<IEnumerable<T>>` for `DataAsync` parameter. 
However, when we try to return back data from EF Core with `ToListAsync()` we have a `List<T>` 

These two limitations don't work well together. 
What do you guys suggest to workaround this?

Currently I'm working with this approach:

```
public async Task<IEnumerable<MyObject>> GetData(CancellationToken ct = default)
{
      // creating new scope because of threading issues concerning EF Core
      using var scope = _serviceScopeFactory.CreateScope();
      using var context = scope.ServiceProvider.GetService<MyContext>();

     return (await context.MyObjects.ToListAsync(ct)).AsEnumerable();
}
```
Would you recommend this way?

Thanks for clarification.

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

I recommend you check the following article where we described DataGrid async binding: [Bind to Data Asynchronously](http://docs.devexpress.devx/Blazor/DevExpress.Blazor.DxDataGrid-1?b=grid-data-async#bind-to-data-asynchronously). 
In your case, it's not necessary to fetch all data by the *ToListAsync* method. It's enough to return the corresponding object from your context. I attached my sample pro
ject where I used the *NWIND* data base. My implementation of the *GetData* method is the following:
```    
    public async Task<IEnumerable<Products>> GetData(CancellationToken ct = default) {
        return context.Products;
    }
```
[GHI162.zip](https://github.com/DevExpress/Blazor/files/5097523/GHI162.zip)

**Comment by sven5** [comment]
Hi @zabelin-vladimir 

Thank you. Your link to the docs doesn't work (any more ?)

Regards
Sven

**Comment by sven5** [comment]
Hi @zabelin-vladimir 

[This](https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxDataGrid-1#bind-to-data-asynchronously) is the correct link of the doc article.

This is extremely helpful, thanks!

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

My apologies, the link was broken. I corrected it now.
