### ISSUE TITLE
size for PopupEditForm

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#163]
Hi @zabelin-vladimir 

The new `PopupEditForm` mode is really great. Thanks for this. 
However, is there any way to increase the width of the popup, i.e. setting CssClass to "modal-xl" ?

Thanks
Sven

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

At the moment our DataGrid doesn't support the corresponding API. As a possible workaround, I recommend you set the *CssClass* property of DxDataGrid to some value ("MyGrid", for example) and add the following CSS rules to your page:
```
    .MyGrid .dxbs-popup-fixed-width {
        max-width: 700px;
    }
```
We discussed the same solution in the following ticket in our Support Center: [DxDataGrid - Why the Edit form is shown in the popup element](https://supportcenter.devexpress.com/ticket/details/t838040/dxdatagrid-why-the-edit-form-is-shown-in-the-popup-element)

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
