### ISSUE TITLE
"DxEditor events": Will you implement support for preventDefault

### ISSUE THREAD

**Issue by drekoo** [DevExpress/Blazor#164]
**Does not work**
  <DxDateEdit @bind-Date="DT" @onkeydown:preventDefault"></DxDateEdit>
**An also (compile time error: The component parameter 'onkeydown' is used two or more times for this component....)**
<DxDateEdit @bind-Date="DT" @onkeydown="OnKeyDown" @onkeydown:preventDefault"></DxDateEdit>
**It works for native UI** 
<input type="date"  @onkeydown="OnKeyDown" @onkeydown:preventDefault/>

For example, we need to increase/decrease date day if +/- key is pressed. But this +/- should not be visible in input control...
Currently, this is not simple to make.

Similar problem reference:
https://stackoverflow.com/questions/60348208/c-sharp-blazor-how-to-prevent-specific-key-on-input-like-in-js-with-e-preventde?noredirect=1&lq=1

**Comment by zabelin-vladimir** [comment]
Hello @drekoo 

We will discuss whether it is possible to support this feature out of the box.
At the moment, I can recommend you the following workaround:
```
<DxDateEdit @bind-Date="DT" @onkeydown="OnKeyDown" __internal_preventDefault_onkeydown />
```
Our team found this solution in [Microsoft source code](https://github.com/dotnet/aspnetcore/pull/14509/files#diff-778e242f8b195bfeb1315181c61185a4):
```
builder.AddAttribute(sequence, $"__internal_preventDefault_{eventName}", value);
```

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
