### ISSUE TITLE
DxDataGrid Cell Editing

### ISSUE THREAD

**Issue by brux88** [DevExpress/Blazor#165]
hi, everyone, but when will you implement the possibility to modify the values ​​in cell, like a wpf grid?

**Comment by zabelin-vladimir** [comment]
Hello @brux88 

The *Inline Edit* feature is in our plans for 2020 year: [Blazor - Roadmap 2020](https://community.devexpress.com/blogs/aspnet/archive/2020/07/09/blazor-roadmap-2020-mid-year-update.aspx). Would you please clarify if you mean this edit mode or some other, for example, [Batch Editing like in our ASP.NET WebForms grid](https://demos.devexpress.com/ASPxGridViewDemos/GridEditing/BatchEditing.aspx)?

**Comment by brux88** [comment]
yes similar to that of webform, but with the functionality also of being able to move between cells with the keyboard, more similar to the one we use in the wpf controller. but is it possible to know when it will be implemented?

**Comment by zabelin-vladimir** [comment]
Hello @brux88

Thank you for your clarification. I cannot give you the exact time frame as to when we will implement this feature. We plan to implement all the features from the roadmap till the end of the year.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
