### ISSUE TITLE
DxDataGrid Edit form closes suddenly - again in 20.1.6

### ISSUE THREAD

**Issue by 314159265meow** [DevExpress/Blazor#166]
Hello DevExpress Team,

I wanted to raise awareness that after the 20.1.6 update, the problem that the DxDataGrid EditForm immediately closes on custom button click exists again.

This is not related to a master-detail view as mentioned in #159, and specifying a `[Key]` attribute as mentioned in [T900420](https://supportcenter.devexpress.com/ticket/details/t900420/datagrid-for-blazor-the-edit-form-is-immediately-closed-on-a-custom-button-click-if-no) does not solve the problem. 

You can reproduce this if you take the attached example from T900420 and uncomment the `[Key]` attribute on line 89 in the `Index.razor` file. The example is build with version 20.1.4 and the problem is fixed there. After you update the project to the current version 20.1.6, the custom edit form immediately closes again even with the `[Key]` attribute.

Regards,
Michael

**Comment by outsidergiant** [comment]
Hi,

Thank you for pointing this out. I was able to reproduce this issue. We will research and update it and will let you know once we have any news.

**Comment by sven5** [comment]
I found exactly the same issue. However, I was able to workaround this using a local cache of the dataSource. See [T930239](https://supportcenter.devexpress.com/ticket/details/t930239/custom-edit-button-no-longer-working-with-v20-1-6) for solution.

**Comment by 314159265meow** [comment]
Hi, thanks for your comment @sven5 , the workaround was quite helpful.

I just tested the new 20.1.7 version and it seems the problem is fixed there. Using the example from T900420 with the new version, the grid behaves as expected. So I think we can close the issue.
