### ISSUE TITLE
Issue with BUnit and DevExpress Blazor

### ISSUE THREAD

**Issue by patvin** [DevExpress/Blazor#167]
We are using [bunit](https://github.com/egil/bUnit) as our unit test framework with DevExpress Blazor. Unfortunately the tests are failing with NullReferenceException. Here stack trace for the error 

```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    EnvironmentInfoBase.RenderScriptLoader(RenderTreeBuilder builder, Guid containerId)
    DxDecoratedComponent.BeforeBuildRenderTree(RenderTreeBuilder builder)
    RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
    DxDecoratedComponent.BuildRenderTree(RenderTreeBuilder builder)
    <.ctor>b__6_0(RenderTreeBuilder builder)
    ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
    Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
    Renderer.ProcessRenderQueue()
    --- End of stack trace from previous location where exception was thrown ---
    TestRenderer.AssertNoUnhandledExceptions()
    TestRenderer.RenderFragmentInsideWrapper(RenderFragment renderFragment)
    TestRenderer.RenderComponent[TComponent](IEnumerable`1 parameters)
    TestContext.RenderComponent[TComponent](ComponentParameter[] parameters)
```

**Comment by zabelin-vladimir** [comment]
Hello @patvin

Unfortunately, this call stack doesn't allow me to determine the cause of this exception. Would you please share a sample project where this issue is reproduced? I need to research it locally to find out if this exception relates to our components.

**Comment by patvin** [comment]
Hello @zabelin-vladimir ,
Thanks for looking into this issue. Here is a little more background on what I am trying to do. I am trying to write a unit test using a package called [bunit ](https://github.com/egil/bUnit) and whenever it trying to render a component for a unit test I am getting the mentioned error.I am attaching a sample solution that reproduces this error. To reproduce the error open solution in VS2019 and build. Go to TestExplorer and try to run "Test1" unit test(The component is BugTest.razor).I am expecting to execute this test case with no errors. The error is due to DxButton(or any other devexpress control) in BugTest.razor component. I think devexpress should allow me to inject mocked dependencies or consider the case that the renderer could be called from the unit test framework. I would be happy to answer if you have any other questions.

Appreciate your help.

[DxBlazorWebAssemblyApp1.zip](https://github.com/DevExpress/Blazor/files/5164412/DxBlazorWebAssemblyApp1.zip)

**Comment by zabelin-vladimir** [comment]
Hello @patvin

We researched this exception and modified your sample to make it work properly. Please check the attached project and try to use the same approach in your real project.

[DxBlazorWebAssemblyApp1.zip](https://github.com/DevExpress/Blazor/files/5176157/DxBlazorWebAssemblyApp1.zip)

**Comment by egil** [comment]
Hey @zabelin-vladimir 

Creator of bUnit here.

Thanks for your help with this. Might I suggestion the following solution that uses [bUnits built](https://bunit.egilhansen.com/docs/test-doubles/mocking-ijsruntime.html) in mock of `IJSRuntime `(untested, do not have access to the DevExpressBlazor nuget package). It would look something like this:

```c#
public static class DevExpressBunitServicesExtensions
{
    public static TestServiceProvider AddBunitDevExpressBlazor(this TestServiceProvider services)
    {
        services.AddDevExpressBlazor(configure => configure.SizeMode = DevExpress.Blazor.SizeMode.Medium);
        services.AddOptions();
        services.AddSingleton<IEnvironmentInfo, MockEnvironmentInfo>();

        var mockJs = services.AddMockJSRuntime();

        // Here we just need to know what "identifier" will be reiceived with the ApiSchema and DeviceInfo
        // calls, to make the mocking framework match it. 
        mockJs.Setup<ApiScheme>("???").SetResult(new ApiScheme(true));
        mockJs.Setup<DeviceInfo>("???").SetResult(new DeviceInfo(false));

        return services;
    }

    private class MockEnvironmentInfo : IEnvironmentInfo
    {
        private static readonly DateTime DateTimeNow = DateTime.Now.Date;
        public DateTime GetDateTimeNow() => DateTimeNow;
        ValueTask<ApiScheme> IEnvironmentInfo.ApiScheme => new ValueTask<ApiScheme>(new ApiScheme(true));
        ValueTask<DeviceInfo> IEnvironmentInfo.DeviceInfo => new ValueTask<DeviceInfo>(new DeviceInfo(false));
        public Task InitializeRuntime() => Task.CompletedTask;
        public void RenderScriptLoader(RenderTreeBuilder builder, Guid containerId) { }
        public string ResolveUrl(string url) { return url; }
        public void OnMessage(int msg) { }
        public void Dispose() { }
    }
}
```

Super duper extra bonus points if DevExpress published and maintained an extension class like the one above.

```c#
public class UnitTest1 : TestContext
{
    [Fact]
    public void Test1()
    {
        Services.AddBunitDevExpressBlazor();

        var cut = RenderComponent<BugTest>();

        cut.Find("h3").MarkupMatches("<h3>BugTest</h3>");
    }
}
```

**Comment by patvin** [comment]
@egil Sorry I didnt update the issue but I am only using the MockEnvironmentInfo from the solution and I am using the bunit's AddMockJSRuntime
