### ISSUE TITLE
DxComboBox cannot be inferred

### ISSUE THREAD

**Issue by grahamglover** [DevExpress/Blazor#169]
Hi,

Trying to add a DxComboBox to the example projects and i get error below.  DxDataGrid is fine - seems to be specific issue with DxComboBox. Latest VS 2019 Community and .NET Core SDK.

![image](https://user-images.githubusercontent.com/43458536/92723334-44a7e600-f3ac-11ea-8885-6a91e30b95d9.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0411	The type arguments for method 'TypeInference.CreateDxComboBox_1<TData, TValue>(RenderTreeBuilder, int, int, IEnumerable<TData>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	DxBlazorHostedWebAssemblyApp1.Client	C:\Users\grahamg\source\repos\DxBlazorHostedWebAssemblyApp1\DxBlazorHostedWebAssemblyApp1.Client\Pages\DataGrid.razor	1	Active

**Comment by zabelin-vladimir** [comment]
Hello @grahamglover

It's necessary to specify the TData and TValue parameters since you didn't bind the *Value* property to a field.
TData - The data item type.
TValue - The value type.

```
<DxComboBox Data="Cities" TValue="string" TData="string"></DxComboBox>
```

Please specify these parameters and let me know if it helps.
