### ISSUE TITLE
[question] Does DxDataGrid support validation for built-in EditForm?

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#170]
Hi support team,

just a question: 
Imagine I don't use the `EditFormTemplate` but my model requires validation through DataAnnotations - Does the `DxDataGrid` automagically :smile:  generate an `EditForm` with validation support? Or do I have to manually create the `EditForm `if I want validation support?

If not - that would be one nice addition for future updates.

Thanks!
Sven

**Comment by zabelin-vladimir** [comment]
Hello @sven5 

At the moment DxDataGrid doesn't support validation out of the box. So, it's necessary to create the *EditFormTemplate* and add *EditForm* manually.
Thank you for your feedback!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
