### ISSUE TITLE
Stop Creating Setup File

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/Blazor#171]
How can I have Devexpress stop creating the Startup.Devexpress.cs file everytime I build?  It gets annoying to delete it all the time.

I added the reference like this:

```c#
public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddDevExpressBlazor();
        }
```

**Comment by outsidergiant** [comment]
Hi.

We added to the Startup.DevExpress.cs file describing how to stop generating this file. Please add the following line to your project file:
```xml
<DxExtendStartupHost>False</DxExtendStartupHost>
```
It should help.
