### ISSUE TITLE
DxTagBox validation issue

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/Blazor#172]
See attached project.

[BlazorApp23.zip](https://github.com/DevExpress/Blazor/files/5242589/BlazorApp23.zip)

Delete the two preselected tags and then select a new tag - the required error message appears. The required error message disappears only when another item is selected

**Comment by outsidergiant** [comment]
Hi.

Thank you for pointing this out. I was able to reproduce this issue and created the following report:
[TagBox for Blazor - A validation error message is incorrectly shown after clearing initially selected items and selecting another item](https://supportcenter.devexpress.com/ticket/details/t933265/tagbox-for-blazor-a-validation-error-message-is-incorrectly-shown-after-clearing)
We will update it once we have any news.

**Comment by outsidergiant** [comment]
We've fixed the issue. The fix will be included in the next v20.1.7 maintenance update.
