### ISSUE TITLE
DxTagBox filtering does not work depending on configuration

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/Blazor#173]
See attached project.

[BlazorApp23.zip](https://github.com/DevExpress/Blazor/files/5242604/BlazorApp23.zip)

Filtering does not work - I think it's related to having the list as ListRenderMode = ListRenderMode.Virtual along with having multiple columns.

**Comment by outsidergiant** [comment]
Hi,

Thank you for your sample project. I was able to reproduce the issue and created the report below dedicated to this issue:
[TagBox for Blazor - The "Collection was modified; enumeration operation may not execute" error occurs if filtering by multiple columns is performed](https://supportcenter.devexpress.com/ticket/details/t933267/tagbox-for-blazor-the-collection-was-modified-enumeration-operation-may-not-execute).
"Star" it to be notified once its status changes.

**Comment by outsidergiant** [comment]
We've fixed the issue related to ListRenderMode. The fix will be included in the next v20.1.7 maintenance update.
