### ISSUE TITLE
DxDataGrid without borders?

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#174]
Hi support team,

`DxDataGrid` currently renders with bootstrap's css class `table-bordered`:

`<table class="dxbs-table table table-bordered table-sm">`

Is there any way to suppress borders? 
Perhaps you could implement a property `BorderMode` for the `DxDataGrid`.

Thanks
Sven

**Comment by outsidergiant** [comment]
Hello @sven5 ,

Thank you for your suggestion. I'll share it with the team. In the meantime, you can apply custom CSS rules to the grid by setting a marker CSS class via the **CssClass** property and writing a corresponding selector which will remove borders from the grid.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
