### ISSUE TITLE
DxDataGrid ignores previous rendering for new items

### ISSUE THREAD

**Issue by mwpowellhtx** [DevExpress/Blazor#176]
I'm not sure what I'm doing wrong... But when I update the Blazor Server collection, the rendering goes all wonky.

One list is rendered as follows with some default values. Seems well and good.

![image](https://user-images.githubusercontent.com/1824187/95026466-910adc80-065f-11eb-82a2-666601eb9f4a.png)

However, when I click the `+` in the `Queued` grid, I get the following.

![image](https://user-images.githubusercontent.com/1824187/95026510-bb5c9a00-065f-11eb-8e4d-738943f78779.png)

Under the covers I am not doing anything that magical, I don't think:

```Razor
@foreach (var lane in new[] { JobLaneKind.Queued, JobLaneKind.Benched, JobLaneKind.Postponed })
{
    <LaneComponent Jobs="this.Jobs[lane]" CurrentLane="lane" />
}
```

The `Jobs` being given a dictionary `IList<T>` value.

With the LaneController being this reusable component:

```Razor
<DevExpress.Blazor.DxDataGrid T="Job" Data="@this.Jobs" ShowFilterRow="false" @ref="this.ThisGrid" InitNewRow="@this.OnInitNewRow">
    <DevExpress.Blazor.DxDataGridCommandColumn>
        <HeaderCellTemplate>
            <a class="oi oi-plus" @onclick="@(() => this.ThisGrid.StartRowEdit(null))" href="javascript:void(0);"></a>
        </HeaderCellTemplate>
        <CellTemplate>
            <a class="oi oi-pencil" @onclick="@(() => this.ThisGrid.StartRowEdit(context))" href="javascript:void(0);"></a>
            <a class="oi oi-x" @onclick="@(() => this.OnDeleteItem(context as Job))" href="javascript:void(0);"></a>
        </CellTemplate>
    </DevExpress.Blazor.DxDataGridCommandColumn>
    <DevExpress.Blazor.DxDataGridColumn Field=@nameof(Job.Id) />
    <DevExpress.Blazor.DxDataGridColumn Field=@nameof(Job.CurrentLane) />
    <DevExpress.Blazor.DxDataGridColumn Field=@nameof(Job.Text) Caption="@($"{nameof(Job.Text)}")" />
    <DevExpress.Blazor.DxDataGridDateEditColumn Field=@nameof(Job.UpdatedOn) DisplayFormat="dd/MM/yyyy" EditorVisible="false" />
</DevExpress.Blazor.DxDataGrid>
```

And the OnInitNewRow simply doing this:

```C#
Task OnInitNewRow(Dictionary<string, object> values)
{
    this.Jobs.Add(new Job { CurrentLane = this.CurrentLane });
    return Task.CompletedTask;
}
```

It's trying to render, but good LORD, what fell over in the process? And how can I help it, if possible?

**Comment by mwpowellhtx** [comment]
Eventually I might like to somehow facilitate a drag drop, or at least a remove from one, insert in the other, type of procedure. Eventually... Is there any way to help that behave better? Perhaps short of completely re-rendering one of the elements.

**Comment by mwpowellhtx** [comment]
So I did not see the whole screen apparently. Still, I would like to go from "adding" to simply "added" and skip the unnecessary, and ugly looking, `(x)` bits. There is the `"Update Cancel"` buttons to consider there.

![image](https://user-images.githubusercontent.com/1824187/95026662-f14e4e00-0660-11eb-9067-ea1c40b7c9a0.png)

Suggestions how I can possibly configure the data grid (or tree view, or whatever) along these lines?

**Comment by mwpowellhtx** [comment]
And a quick update, after a bit of work, I wired up a context menu to help move items between data grids. However, it does not seem to work, or at least not at a underlying collection level. Which leads me to believe that whatever got rendered is at the HTML level, or that I might need to hang on to a reference to each grid itself, if possible, and use its data properties to manipulate its data.

**Comment by mwpowellhtx** [comment]
I think I see... The `DxDataGrid<T>.Data` itself is null. But, and maybe this has to do with historical DX reasons where the approach is concerned, `DxDataGrid<T>.DataContainer.Data` does reference the `List<T>`. If so that would be sufficient, perhaps, to effect additions or removals managing items between display containers, would it not?

**Comment by mwpowellhtx** [comment]
Short of being able to render my items as cards, a context menu approach seems to work, for the most part. The best I seem to be able to do is connect to an _ellipse_ in the `CellTemplate`, i.e.

```Razor
<a class="oi oi-ellipses" @onclick="@(e => this.OnEllipsesShowContextMenu(context, e))" href="javascript:void(0);" />
```

I'd like to do something like this for the entire row, however, somehow:

```Razor
<a class="oi" @oncontextmenu="@(e => this.OnEllipsesShowContextMenu(context, e))" href="javascript:void(0);" />
```

But I cannot find where to place it, that will also have access to the _context_, the data object behind the row.

**Comment by zabelin-vladimir** [comment]
Hello @mwpowellhtx 

We are going to address technical requests only in our Support Center. As I see, you have already created several tickets and some of them relate to the question from this thread. 
Please feel free to create other tickets in our Support Center if some questions from this thread are still actual.

Regards,
Vova
