### ISSUE TITLE
Data grid grouping collapse icon invisible

### ISSUE THREAD

**Issue by mwpowellhtx** [DevExpress/Blazor#177]
Is there something I need to do in order to show the grouping icon in the cell template? In its present form, it is pretty useless.

![image](https://user-images.githubusercontent.com/1824187/95109643-df28ea00-070a-11eb-9982-2eed0b8e11bb.png)

Secondary, what's with the huge black `(x)` images? Lack of an editor? How about just not showing those when there is no editor, or an editor simply does not make any sense? Or is this something I need to also declare via the cell and/or edit templates? Which is fine, I'd just like to be more informed about how to handle those scenarios.

Cheers, thank you so much.

**Comment by mwpowellhtx** [comment]
Additionally, while grouping is interesting, I might still like to edit the column upon which grouping occurred. I do not know if this is possible in its current form. Which, when that might occur, the row would automatically regroup into the appropriate group, ordered, etc, and so on.

![image](https://user-images.githubusercontent.com/1824187/95109810-17c8c380-070b-11eb-90ce-79fded9e79b1.png)

**Comment by zabelin-vladimir** [comment]
Hello @mwpowellhtx

As for the abnormal size of the clear buttons, I assume that our client styles are not loaded properly. We have discussed a similar issue in this thread in our Support Center: [ComboBox for Blazor is rendered incorrectly](https://supportcenter.devexpress.com/ticket/details/t852546/combobox-for-blazor-is-rendered-incorrectly).

If this information doesn't help you (or you have any other questions regarding our components), please create a new ticket in our [Support Center](https://www.devexpress.com/ask) and attach the problematic project to this thread.

Regards,
Vova

**Comment by mwpowellhtx** [comment]
Appreciate the response, @zabelin-vladimir that did it. I do have a [follow on question](https://supportcenter.devexpress.com/ticket/details/t937274/blazor-data-grid-incorrectly-bound-to-source-context) however.
