### ISSUE TITLE
Is it possible to pass node collection data to DxTreeView nodes?

### ISSUE THREAD

**Issue by euroUK** [DevExpress/Blazor#18]
Is it possible to pass node collection data to DxTreeView nodes?

There is Data property on DxDataGrid, but I didn't find this on DxTreeView to dynamically create tree view.

Thank you!

**Comment by SergeySeleznyov** [comment]
Hi @euroUK ,

There is no Data-like property in this first Tree View version. This will be implemented in one of the following versions.
But you can do it in your code:

some.razor file:
```
<DxTreeView... >
  <Nodes>
    @foreach (var product in Products)
    {
             <DxTreeViewNode Text=@"GetTextFormProduct(product)">
                <Nodes>
                     @foreach (var part in product.Parts) 
                     {
                         <DxTreeViewNode Text=@"GetTextFormPart(part)">
                         </DxDataGridRow>
                     }
                </Nodes>
         </DxDataGridRow>
    }
  </Nodes>
</DxTreeView>
```

Please try this approach and let us know whether it is helpful. You can also share your ideas and wishes about the future Data-like property?
 
Thank you!

**Comment by SergeySeleznyov** [comment]
Yury, thank you for the explanation.
 
Do you have items of the same type on each level of a hierarchy?

**Comment by BenHayat** [comment]
> There is no Data-like property in this first Tree View version. This will be implemented in one of the following versions.

Ah, I was about to ask about that.
Hopefully you will support Self-referencing data, i.e. like Explorer folder structure or father/child type, where all the nodes come from the same datasource.

**Comment by euroUK** [comment]
> Yury, thank you for the explanation.
>  
> Do you have items of the same type on each level of a hierarchy?

Thank you Sergey. For me same type will be enough. I can use some generic interface if I need.

**Comment by SergeySeleznyov** [comment]
Yury, Ben, 
 
Thank you both for your time and explanation.
I understood your scenarios. We will support the API you described in one of the future updates.
 
Thank you guys, I appreciate your help.

**Comment by BenHayat** [comment]
Sure Sergey;
Great to work with you.

**Comment by Nelda4** [comment]
Hi @euroUK and @BenHayat,
 
We've just released the TreeView component's data binding feature. The sample scenarios are already available on the [TreeView demo page](https://demos.devexpress.com/blazor/TreeView) (**TreeView - Binding to Hierarchical Data** and **TreeView - Master-Detail Data Binding** sections). Would you please check them and let us know whether the implementation meets your scenarios' requirements? 
 
Thank you!
