### ISSUE TITLE
Question about roadmap or reusing existing libraries.

### ISSUE THREAD

**Issue by sdanyliv** [DevExpress/Blazor#21]
What can I say, i really like your web libraries. Kudos for you. I'm just trying to understand what I can reuse ore simulate if they are not ready.

- Reporting is must for my current task, not with a designer for now, but how I can use existing reprots viewer in Server-side Blazor?
- Charts, also interesting, for now I can accept server-side also.

**Comment by e1em3ntoDX** [comment]
Hi,

Thank you for your compliments. In case of Reporting tools, I suggest that you review a sample project attached in this Support Center thread: https://www.devexpress.com/Support/Center/Question/Details/T753291/using-devexpress-asp-net-core-components-in-a-blazor-project. While this approach is not that straightforward and can be only considered as a workaround, this is the only possible way to integrate our Reporting tools into Blazor app.

**Comment by e1em3ntoDX** [comment]
Let me share another thought about the "simulation" of missing Blazor components that came to my mind: you can develop a standalone console .NET Standard 2 application that produces an image's content from a Chart/Report that you can bind to your data. The generated image content can be delivered from the server by some Id or even nested right inside the HTML page as base64 content:

`<div>
<p>Taken from wikipedia</p>
<img src="data:image/png;base64, ...==" alt="Chart" />
</div>`
 
Then, you can reuse the same code in the server-side Blazor. Developing a console application will make development and debugging easier than it is in Blazor. In other words, if you can implement such a console application, nothing will prevent you from running the same code in the server-side Blazor. After that, you can just move the code into some dll or include the code into your server-side Blazor project.

**Comment by sdanyliv** [comment]
@e1em3ntoDX, thank you for your help. Will check what i can do in such situation. Maybe mixing MVC, Razor Components pages.
I have found interesting workaround that i need to check
https://stackoverflow.com/questions/56241125/adding-server-side-blazor-to-an-existing-mvc-core-app

**Comment by e1em3ntoDX** [comment]
@sdanyliv Thank you for sharing that interesting workaround with us! Let us know if you have any other questions.

**Comment by sdanyliv** [comment]
Thanks, you can close this question if you do not need it for tracking purposes.
