### ISSUE TITLE
Grid Pagination suggestion

### ISSUE THREAD

**Issue by sdanyliv** [DevExpress/Blazor#22]
Hi,

I have noticed, that grid accepts IQueryable as a source, very good. But I assume that for pagination you have used two queries: `query.Count()` and `query.Skip(...).Take(...)`
It is common approach for EF. But EF is not one way to work with database, there are many linq providers and some of them support Window Functions and I can retrieve Count and payload in one roundtrip to database - for example https://github.com/linq2db/linq2db/issues/1402#issuecomment-438961009. 
I'm proposing to add additional interface. Something like this:
```cs
public interface IQueryPaginator
{
	Tuple<int, List<T>> Paginate<T>(IQueryable<T> query, int page, int pageSizes)
	Task<Tuple<int, List<T>>> PaginateAsync<T>(IQueryable<T> query, int page, int pageSizes)
}
```
In this case we can intercept default behaviour.

Also, does grid supports grouping, summaries, etc.?

**Comment by SergeySeleznyov** [comment]
Hi Svyatoslav,
 
Grid accepts IEnumerable<T> as the Data property value, but inside it tries to cast it to IQueryable<T> and operates with data as IQueryable if possible.
Please review the demo: https://demos.devexpress.com/blazor/GridLargeDataBase
> a dataset that contains a million rows ...
> Entity Framework Core (version 3.0) provides DxDataGrid with an IQueryable<T> source.
 
The grid's data core supports grouping and summaries, but its public API and render are not implemented yet.
Please see the roadmap: https://community.devexpress.com/blogs/aspnet/archive/2019/06/24/blazor-roadmap-what-you-can-expect-in-the-next-few-months-from-devexpress.aspx
The Grouping is in the list.

Should you have any questions about the Blazor Grid's data core, you may also visit its github repository:
https://github.com/DevExpress/DevExtreme.AspNet.Data

**Comment by sdanyliv** [comment]
You didn’t get idea, i don not want to change Data property. I suggest to add another DataPaginator to reduce Database roundtrips. I know everything about IQueryable and how it works.

**Comment by SergeySeleznyov** [comment]
It would be better to discuss Grid's data fetching in the DevExtreme.AspNet.Data project.
I've passed your suggestion to the DevExtreme.AspNet.Data maintainer. It appears there is some question to your suggestion there. 
Would you please repost this suggestion to the [DevExtreme.AspNet.Data project's github](https://github.com/DevExpress/DevExtreme.AspNet.Data)?

**Comment by sdanyliv** [comment]
Yes, sure. Thank you for pointing me in right github repository.
