### ISSUE TITLE
Nullable DateTime Edit in the Grid

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#23]
Hi, Will you please provide a sample of editing a nullable Datetime field in the Grid? I tried below approach,  it displayed properly, however the updated value did not make to the OnRowUpdated's newValuel.  Apologies somehow the linebreaks can't be pasted properly here.

thanks

`<DxDataGridDateEditColumn Field=@col.Name>
                                <EditTemplate>
                                    @{
                                        var cellEditContext = (CellEditContext)context;
                                        string str = cellEditContext?.CellValue?.ToString();
                                        var datevalue = string.IsNullOrEmpty(str) ? DateTime.MinValue : DateTime.Parse(str);
                                        <DxDateEdit @bind-Date=@datevalue></DxDateEdit>
                                    }
                                </EditTemplate>
                            </DxDataGridDateEditColumn>`

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc ,

Would you please try this example and let us know if it meets your requirement?

```c#
    <DxDataGrid Data=@DataSource
                AllowRowSelection=true
                ShowFilterRow=false
                RowRemoving=@((dataItem) => OnRowRemoving(dataItem))
                RowUpdating=@((updatingDataItem, newValues) => OnRowUpdating(updatingDataItem, newValues))
                RowInserting=@((newValues) => OnRowInserting(newValues))>

        <DxDataGridCommandColumn Width="150px"></DxDataGridCommandColumn>

        <DxDataGridColumn Field=@nameof(MyDataType.Id) Caption="Id" Width="50px"></DxDataGridColumn>

        <DxDataGridColumn Field=@nameof(MyDataType.NullableDateTime) Caption="Nullable DateTime">
            <EditTemplate>
                @{
                    var cellEditContext = (CellEditContext)context;
                    string str = cellEditContext?.CellValue?.ToString();
                    var datevalue = string.IsNullOrEmpty(str) ? DateTime.MinValue : DateTime.Parse(str);
                    <DxDateEdit 
                                Date="@datevalue" 
                                DateChanged="@(newCellValue => ((CellEditContext)context).OnChanged(newCellValue))">
                    </DxDateEdit>
                }
            </EditTemplate>
        </DxDataGridColumn>
    </DxDataGrid>

@code{
    public class MyDataType {
        public string Id { get; set; }
        public DateTime? NullableDateTime { get; set; }
    }

    IEnumerable<MyDataType> DataSource;

    protected override void OnInit() {
        DataSource = new List<MyDataType>() {
            new MyDataType() { Id = "1" },
            new MyDataType() { Id = "2", NullableDateTime = DateTime.Now }
        };
    }

    void OnRowRemoving(MyDataType dataItem) {
        // ...
    }
    void OnRowUpdating(MyDataType dataItem, Dictionary<string, object> newValue) {
        foreach (var field in newValue.Keys) {
            switch (field) {
                case "id":
                    dataItem.Id = (string)newValue[field];
                    break;
                case "NullableDateTime":
                    dataItem.NullableDateTime = (DateTime)newValue[field];
                    break;
            }
        }
    }
    void OnRowInserting(Dictionary<string, object> newValue) {
        // ...
    }
}
```

Please note the **DateChanged** event handler that notifies the **CellEditContext** of value changed by the custom editor.

```c#
<DxDateEdit 
    Date="@datevalue" 
    DateChanged="@(newCellValue => ((CellEditContext)context).OnChanged(newCellValue))">
</DxDateEdit>
```


Best Regards

**Comment by goldmannyc** [comment]
Thanks for the prompt response, it worked perfectly!

**Comment by nkritikos** [comment]
Hi Sergey,
DateTime.MinValue  or DateTime.Now (as mentioned in other similar posts) is not a very clear solution.
Are there any plans for nullable datetime in grid as well as in standalone dxDateEdit ?
Thank you

**Comment by SergeySeleznyov** [comment]
Hi @nkritikos,

Thank you for bringing our attention to this example. You are right, this example was not clear.
Fortunately, we can improve this code now.

> Are there any plans for nullable datetime in grid as well as in standalone dxDateEdit ?

Sure, working with null values is a "must have" feature for the editors (and for the grid's columns too).
This feature is already released, but is currently used only for internal purposes (in DataGrid's filtering row).
We have not provided this feature for public use yet, so you can use the internal API.*

* *Please note, the internal API can be modified or removed when the public one is completed.*

The component could look as follows - DateEditNullable.cs

```c#
using System;
using Microsoft.AspNetCore.Components;

namespace DevExpress.Blazor {
    public class DateEditNullable : DxDateEdit {
        [Parameter] public object Value { get => DateEditState.GetValue(); set => DateEditState.SetValue(value); }
        [Parameter] public Action<object> ValueChanged { get; set; }

        protected override bool AllowClearButton { get => true; }

        public DateEditNullable() {
            AllowNullInternal = true;
        }

        protected override void OnValueChangedInternal() {
            ValueChanged?.Invoke(Value);
            base.OnValueChangedInternal();
        }
    }
}
```

Standalone DateEdit with a nullable value could be as follows - Index.razor:

```razor
@page "/"

<p>@NullableDateTime</p>
<DateEditNullable @bind-Value="@Value"></DateEditNullable>

@code {
    public DateTime? NullableDateTime { get; set; } = null;
    public object Value { 
		get => NullableDateTime;
		set { 
			if (NullableDateTime != (DateTime?)value) { 
				NullableDateTime = (DateTime?)value; 
				InvokeAsync(StateHasChanged); 
			} 
		} 
	}
}
```

DxDataGrid with the Nullable DateTime column could be as follows - Index.razor:

```razor
@page "/"

<DxDataGrid Data=@DataSource
            AllowRowSelection=true
            ShowFilterRow=false
            RowRemoving=@((dataItem) => OnRowRemoving(dataItem))
            RowUpdating=@((updatingDataItem, newValues) => OnRowUpdating(updatingDataItem, newValues))
            RowInserting=@((newValues) => OnRowInserting(newValues))>

    <DxDataGridCommandColumn Width="150px"></DxDataGridCommandColumn>

    <DxDataGridColumn Field=@nameof(MyDataType.Id) Caption="Id" Width="50px"></DxDataGridColumn>

    <DxDataGridColumn Field=@nameof(MyDataType.NullableDateTime) Caption="Nullable DateTime">
        <EditTemplate>
            @{
                var cellEditContext = (CellEditContext)context;
                object nullableDateTime = cellEditContext?.CellValue;
                Action<object> ValueChanged = (newCellValue) => {
                    cellEditContext.OnChanged(newCellValue);
                };

                <DateEditNullable Value="@nullableDateTime" ValueChanged="@ValueChanged"></DateEditNullable>
            }
        </EditTemplate>
    </DxDataGridColumn>
</DxDataGrid>

@code{
    public class MyDataType
    {
        public string Id { get; set; }
        public DateTime? NullableDateTime { get; set; }
    }

    IEnumerable<MyDataType> DataSource;

    protected override void OnInitialized()
    {
        DataSource = new List<MyDataType>() {
            new MyDataType() { Id = "1", NullableDateTime = null },
            new MyDataType() { Id = "2", NullableDateTime = DateTime.Now }
        };
    }

    void OnRowRemoving(MyDataType dataItem)
    {
        // ...
    }
    void OnRowUpdating(MyDataType dataItem, Dictionary<string, object> newValue)
    {
        foreach (var field in newValue.Keys)
        {
            switch (field)
            {
                case "id":
                    dataItem.Id = (string)newValue[field];
                    break;
                case "NullableDateTime":
                    dataItem.NullableDateTime = (DateTime?)newValue[field];
                    break;
            }
        }
    }
    void OnRowInserting(Dictionary<string, object> newValue)
    {
        // ...
    }
}
```

After the feature is completed, DxDataGridDateEditColumn will work with this scenario without additional code.

I'm reopening this issue in case somebody would be also interested in this solution.

Could you please check this approach in your project and say if any feature is missing?
Thank you @nkritikos!

**Comment by nkritikos** [comment]
Hi Sergey,
I just tested the standalone editor with DateEditNullable inherited class and works fine .
I will test it as grid column also
Thank you for your immediate response

**Comment by outsidergiant** [comment]
Hello everyone, 

I'm happy to inform you that inthe latest release (19.1.10) the Date Edit component and the Date Edit DatаGrid column can be bound to a nullable value.

[Demo](https://demos.devexpress.com/blazor/DateEdit#NullableDate)

You can also turn on the Clear Button to drop the value to null.
To display this button set the ClearButtonDisplayMode property to DataEditorClearButtonDisplayMode.Auto.

Please feel free to contact us should you have any feedback or need assistance.

Please feel free to contact us should you have any feedback or need assistance.
