### ISSUE TITLE
Question: Is jQuery being used in DX Blazor components?

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/Blazor#24]
Hello team;

I see, for many stuff, Bootstrap uses jQuery. My question is, are you guys relying on jQuery for Bootstrap support or animations and stuff like that?
If yes, is the usage of jQuery going to continue when we start Blazor Client-side?

When I was using Vue, I noticed most third party component vendors stayed away from the old jQuery library and relied on JS and Vue.

Thanks!
..Ben

**Comment by outsidergiant** [comment]
Hello Ben,

We do not rely on jQuery and are not planning to do so.

Regards.

**Comment by BenHayat** [comment]
Excellent news Paul!
