### ISSUE TITLE
DevExpress grid css classes

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#25]
I gave the DevExpress grid rows some custom css classes but they are overwritten when a row gets selected/deselected. Can you toggle your row selection/deselection css classes instead of overwriting them?

Thanks!

**Comment by outsidergiant** [comment]
Hi,
 
Would you please clarify how do you set custom CSS classes? I tried to reproduce the issue by setting the DataRowCssClass property to the "my-row-css custom" value, but these classes were not overwritten. 
![CssClasses](https://user-images.githubusercontent.com/17219648/60877995-8fc5e680-a247-11e9-8abf-78e1bc655229.png)
Please provide me with the steps to reproduce the problematic behavior.

**Comment by rysep2** [comment]
Oh ok I see now how you would usually add custom css classes. In my case I used jquery draggable on the rows with the following JS:
`    $("#devExGrid").find("tr").draggable({
        connectToSortable: ".sortable",
    });`
So the css classes are automatically created by jQuery UI..

**Comment by outsidergiant** [comment]
The behavior you observe when using jQuery UI is related to the Blazor "Virtual DOM" technique. Take a look at [Sergey's post](https://github.com/DevExpress/Blazor/issues/14#issuecomment-507569190).
 
To set CSS custom classes, I recommend using our API: **CssClass** and **DataRowCssClass** properties. Let me know if it meets your needs.
