### ISSUE TITLE
Virtual Scrolling -- horizontal scroll?

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#27]
The new virtual scrolling feature looks promising, Is there a way to add horizontal scroll for datasets with large number of columns?

The popup editing form looks nice too,  is there way to add validation in this mode without rewriting the grid display logic as in the Edit Form Validation Sample?

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc ,
 
Thank you for your kind words.
 
The features are not implemented but both of them are in our backlog:
- Scrollbars for paging (without "Virtual Scrolling")
- Built-in edit form data validation
You have already found a way to work around the missing built-in validation.
As for the first feature, it is possible to use a custom CSS for "Virtual Scrolling", still this may be inconvenient. Would you please clarify how critical the lack of this feature is in your project?

**Comment by goldmannyc** [comment]
The Scrollbars for paging is important for our project, as the datasets in the project have large number of columns and we are struggling with the views.

**Comment by SergeySeleznyov** [comment]
Thank you for the update. We have increased the priority for this task.
Hope to deliver it shortly.
 
Thank you!

**Comment by goldmannyc** [comment]
That would be great, thank you for your prompt response.

**Comment by SergeySeleznyov** [comment]
You are always welcome, @goldmannyc .

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc ,

Would you please check [scrolling in the Data Grid demo](https://demos.devexpress.com/blazor/GridScrolling) and let us know whether it meets your scenario's requirements?

Thank you for you feedback. It is very valuable for us.

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc ,
 
I hope the new feature is working for you and I'm closing the issue. Please feel free to reopen it should you have any difficulty with it.
