### ISSUE TITLE
DxDataGrid - Key up/down should move the selection

### ISSUE THREAD

**Issue by bitdeploy** [DevExpress/Blazor#29]
Hi!

the up/down keys should move the selection

please see https://demos.devexpress.com/ASPNetCore/Demo/DataGrid/FocusedRow/

regards,
Michael

**Comment by outsidergiant** [comment]
Thank you, Michael. We plan to implement all main ASP.NET controls features in pour Blazor components. Keyboard support is in our future plans.

Would you please clarify whether you have experience with other DevExpress products? What components and features do you use in your projects?

**Comment by bitdeploy** [comment]
We have experience developing large LOB applications using DX WinForms, mainly using DocumentManager, DataLayoutControl, XtraGrid, XtraReports and XPO ORM. Some of our customers are planning or have already migrated to Azure. Because of this we are evaluating ASP.NET core (MVC/DevExtreme) and Blazor.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
