### ISSUE TITLE
When using Scrolling features,  the left border of the grid is invisible.

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#30]
This is consistent in all the Scrolling samples in the serverside demo.

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc,
 
I've checked [our demos](https://demos.devexpress.com/blazor/GridScrolling)
and see that the Data Grid has a border in both scrolling directions.
 
I've also created a new project from scratch, and used separate grids for each scrolling direction.
Both grids have borders: 
![image](https://user-images.githubusercontent.com/950357/62192860-26854f00-b37f-11e9-948e-c5eef5d260ca.png)

Can you see something wrong in this picture?
 
If the grid in my examples looks OK to you, would you please ensure that you have updated the static files in your project?
You can take the latest static files from [this repository](https://github.com/DevExpress/Blazor/tree/master/client-runtime).

**Comment by goldmannyc** [comment]
Hmmm, it is a little strange.  We were actually running your latest demo (server side) locally  without any changes,  only the grids with scrolling have no left border,  the rest of the grids are fine.

![image](https://user-images.githubusercontent.com/33879259/62250950-5868d680-b3bc-11e9-881b-89c312f16b01.png)

![image](https://user-images.githubusercontent.com/33879259/62251009-79312c00-b3bc-11e9-81bb-2e3c61fe31c1.png)

**Comment by outsidergiant** [comment]
Hi,
 
I tested the grid with enabled scrolling and the same Dependencies as in your screenshot but wasn't able to reproduce the issue in Chrome, Firefox, and Edge browsers. Would you please clarify what browser you use? Does this issue happen in only in a certain browser or in all browsers? Is zooming enabled there? Do you see this issue while testing [our online demos](https://demos.devexpress.com/blazor/GridScrolling)? If not, execute the `git clone` command to clone demo files into an empty folder and test how it works again. 
If this issue can be reproduced on your side even in our demos, try disabling browser plug-ins, add-ons, extensions one by one and let me know if the issue exists.

**Comment by goldmannyc** [comment]
We rebuilt the host and it seemed the problem went away.

thx

**Comment by SergeySeleznyov** [comment]
@goldmannyc 
 
Thank your for the update. I'm happy to hear that everything is OK now.
Feel free to contact us if you have further questions.
