### ISSUE TITLE
Enhancement: DxDataGridComboBoxColumn should have AllowUserInput property

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#32]
Hi @SergeySeleznyov 

I think it would be useful to have the property `AllowUserInput` as well in the `DxDataGridComboBoxColumn`. 

Regards
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,
 
I think you are right.
I added your suggestion to our backlog. I believe, we will be able to do it in the next release.
 
Currently, you can work around it by using a column's EditTemplate.
 
Thank you for your feedback.

**Comment by SergeySeleznyov** [comment]
Could you please elaborate on the behavior you expect to see if an end user types text that does not match any of combobox items (when DxDataGridComboBoxColumn operates some complex types but not strings)?

Does your DxDataGridComboBoxColumn operate string values?

**Comment by howarkdotnet** [comment]
How to change the displayed text"Edit" in datagrid to other languages?

**Comment by sven5** [comment]
Hi @SergeySeleznyov 

Currently I'm using this functionality inside an EditTemplate and only with string values.  The usage with complex types is not that easy. 

However there could be multiple scenarios:

1. Unsupport complex types
2. Create a new object in the collection with behalf of the entered value. This could fail when the collection is no `IList` and when mandatory values are missing (i.e. validation).
3. Allow an "add new" functionality to come in-place when no entered value matches (i.e. by using a popup editor)

Regards
Sven

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
