### ISSUE TITLE
Support for Internet Explorer 11

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#35]
Hi @SergeySeleznyov 

Currently, we're renewing some Intranet applications with the help of Blazor and DevExpress Blazor widgets. Unfortunately, IE 11 is still running on most of the client PCs. 
The problem is that it's not easy to replace all of them at a certain time. However, blazor should support IE 11 and there also is a [polyfill library available](https://github.com/Daddoon/Blazor.Polyfill) to support it. 

Do we have any chance for support IE11? By now it doesn't work, even your demo site dosn't load well in IE 11.

Thanks
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,   
 
While our components are in Preview, they won't support Internet Explorer 11. Please note that only server-side Blazor supports in IE11 and only with polifills:
https://docs.microsoft.com/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0     
 
I tested the https://github.com/Daddoon/Blazor.Polyfill project couple of months ago. It operated OK that time, but noticeably slower than the same project in modern browsers including MS Edge. 
 
I also do not see Internet Explorer 11 issues in the [Blazor Roadmap](https://github.com/aspnet/AspNetCore/issues/8177) to solve in the near future.
 So, we expect performance issues in this browser. It looks like the Blazor team is not going to improve IE11 support.

**Comment by sven5** [comment]
Hi Sergey,

We only need server-side Blazor and we're using Daddoons polyfills already to get it working in IE11. So do you see any chance to support server-side?

Thanks
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,

We are researching how we can support IE11. We will inform you about the progress.

**Comment by sven5** [comment]
Hi @SergeySeleznyov 

Thank you very much. I analyzed for a while and found that you're using ES6 modules for client-side code. I stopped here because IE11 doesn't support it.
While we are revising our legacy Intranet apps we still must support old sites and user's client PCs mostly running IE11. However, it will take us some more months to update all old applications. 

Regards
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,
 
With this update we have fixed some issues with IE11.
You may have it working if you are using:
1. the polyfills collection you mentioned above 
2. a solution for promises, for instance from here https://github.com/stefanpenner/es6-promise#cdn
 
Please note: we do not distribute any of that polyfills and do not use them in our demos.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
