### ISSUE TITLE
Error when using Blazor Form Layout

### ISSUE THREAD

**Issue by euroUK** [DevExpress/Blazor#36]
Good day team!

I'm trying to create simple layout form, but I have error somewhere in JS (it looks like)

```EndInvokeJSFromDotNet[4,false,"Could not find 'DxBlazor' in 'window'.\nError: Could not find 'DxBlazor' in 'window'.\n    at https://localhost:44342/_framework/blazor.server.js:8:27768\n    at Array.forEach (<anonymous>)\n    at d (https://localhost:44342/_framework/blazor.server.js:8:27729)\n    at https://localhost:44342/_framework/blazor.server.js:8:28342\n    at new Promise (<anonymous>)\n    at e.beginInvokeJSFromDotNet (https://localhost:44342/_framework/blazor.server.js:8:28316)\n    at https://localhost:44342/_framework/blazor.server.js:1:19148\n    at Array.forEach (<anonymous>)\n    at e.invokeClientMethod (https://localhost:44342/_framework/blazor.server.js:1:19119)\n    at e.processIncomingData (https://localhost:44342/_framework/blazor.server.js:1:17165)"]```

My code looks like this:
```csharp
<div class="card demo-card-wide">
    <div class="card-header">Test</div>
    <div class="card-body">
        <DxFormLayout>
            <DxFormLayoutItem Caption="Question Text:" ColSpanMd="12">
                <Template>
                    <DxTextBox @bind-Text=@QuestionText></DxTextBox>
                </Template>
            </DxFormLayoutItem>
            <DxFormLayoutItem Caption="Question Name:" ColSpanMd="12">
                <Template>
                    <DxTextBox @bind-Text=@QuestionName></DxTextBox>
                </Template>
            </DxFormLayoutItem>
        </DxFormLayout>

    </div>
 </div>
@code{
        string questionName;
        string QuestionName { get => questionName; set { questionName = value; OnChanged(); } }
        string questionText;
        string QuestionText { get => questionText; set { questionText = value; OnChanged(); } }
}
```

What problem can be here? I have working grids in same project, it looks like DxBlazor should be initialized properly.

**Comment by euroUK** [comment]
Sorry, it looks that changing _Host.cshtml to this solving issue.
```
    <script src="~/lib/dx-blazor/dx-blazor.js"></script>
    <link href="~/lib/dx-blazor/dx-blazor.css" rel="stylesheet" />
```
Could you please add reminder to documentation to check this links?

**Comment by outsidergiant** [comment]
Hi,
 
Thank you for your interest in our components and thank you for informing us that the issue is resolved.
 
While we are still working on our documentation, we have added this information in the README.md file. In particular, in the 6th item of the [How to create a new project](https://github.com/DevExpress/Blazor/#how-to-create-a-new-project) paragraph and the [Troubleshooting](https://github.com/DevExpress/Blazor/#troubleshooting) section.
