### ISSUE TITLE
Is it possible to bind DxDataGridComboBoxColumn  to object value?

### ISSUE THREAD

**Issue by euroUK** [DevExpress/Blazor#37]
Is it possible to bind DxDataGridComboBoxColumn  to object value?
I'm trying to use this code
```
 <DxDataGridComboBoxColumn Field="@nameof(Student.Department)" Caption="Department" TextFieldName="@nameof(Department.Name)" ValueFieldName="@nameof(Department.Id)" Data="@departments"> </DxDataGridComboBoxColumn>
```
but it looks that I'm doing something wrong - no text values (it seems that it is using ToString() by default) as well as sorting or filtering is throwing exception.

Thank you!

**Comment by SergeySeleznyov** [comment]
Hi @euroUK ,
 
Thank your for contacting us.
 
We will support this task to work "out of the box" soon.
For the time being, please use DisplayTemplate/EditTemplate DxDataGridColumn's features as it is shown in the demo:
https://demos.devexpress.com/blazor/GridTemplate
 
Depending on your scenario, you may find either the "Availability" or "Category" column template implementation useful.
I would recommend you get started with the "Availability" column.
 
Put your code translating Value->Text in the DisplayTemplate. The pseudocode may be the following:
 
```
<DisplayTemplate>
    @{
        var value = (context as YourDataItemType).YourColumnValue;
        var selectedComboBoxDataItem = FindObjectByValue(value);
        vat text = selectedComboBoxDataItem.Text;
        <span>@text</span>
    }
</DisplayTemplate>
```
 
Put the DxComboBox into the EditTemplate. The pseudocode may be the following:

```
<EditTemplate>
    @{
        var value = (((YourComplexComboBoxDataItemValueType)((CellEditContext)context).CellValue);
        var selectedComboBoxDataItem = FindObjectByValue(value); // The same like in DisplayTemplate
    }
    <DxComboBox Data="YourComplexComboBoxDataItems"
        SelectedItem="@ selectedComboBoxDataItem"
        SelectedItemChanged="@(newCellValue => ((CellEditContext)context).OnChanged(newCellValue.ValueFieldInYourYourComplexComboBoxDataItems))">
    </DxComboBox>
</EditTemplate>
 ```

Would you please try this approach and let us know should you have any difficulty with it?
 
We see that this should work out of the box. This scenario is of high importance to us.

**Comment by euroUK** [comment]
Thank you!

I will try this aproach and provide feedback. I just want to check how sorting or filtering is working with object properties? It looks that ability to specify lambdas for sorting/filtering would be great in release version.

**Comment by SergeySeleznyov** [comment]
You are always welcome!
 
Currently sorting and filtering work by a column value.
It should be improved when we implement the "Filter enhancements" task.
 
You could get all the features you described if you add the string property to your grid's DataItem type.
In this case, 
- the combobox will work with this string property out of the box;
- sorting and filtering will work with this string property
 
Is it possible to add such a property?

**Comment by euroUK** [comment]
Thank you Sergey!

At this point I can create extra string field and it is the same way I've seen in your examples. I'm looking forward to get version with out-of-box support.

**Comment by SergeySeleznyov** [comment]
Hi @euroUK,
 
We have supported this scenario:

https://demos.devexpress.com/blazor/GridFilterRow

```c#
<DxDataGridComboBoxColumn Field="@nameof(Order.ShipRegionID)"
                          Caption="Ship Region"
                          Data="@ShipRegions"
                          ValueFieldName="@nameof(ShipRegion.RegionID)"
                          TextFieldName="@nameof(ShipRegion.Name)"
                          Width="250px">
```

Would you please check it out and let us know whether you have any difficulty with it?
Thank you for your time!

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
