### ISSUE TITLE
Is it possible to customize labels, appointments and the resource grouping of the scheduler?

### ISSUE THREAD

**Issue by andrew-bird** [DevExpress/Blazor#38]
Hi!

I've just tested DxScheduler component and found some issues:
- It looks like only 7 label colors  are available, all other are white. May be we can add custom dictionary with label colors?
- It would be great to have resource column within each day, e.g. free rooms/cars e.t.c
- RecurrenceInfo syntax looks too complicated, in my opinion it should be either or object or separate fields.
- Is it possible to customize appearance of appointment items?

_Originally posted by @euroUK in https://github.com/DevExpress/Blazor/issues/4#issuecomment-525451411_

**Comment by andrew-bird** [comment]
Hello @euroUK ,

> It looks like only 7 label colors are available, all other are white. May be we can add custom dictionary with label colors?

Yes, there is such a possibility. DxSchedulerDataStorage allows you to define a custom collection of labels and statuses. Use the AppointmentLabelsSource and AppointmentLabelMappings properties to define a custom label collection.

```c#
public class LabelItem {
    public int Id { get; set; }
    public Color CustomColor { get; set; }
    public string CustomCaption { get; set; }
}

DxSchedulerDataStorage DataStorage = new DxSchedulerDataStorage() {
    AppointmentLabelsSource = new List<LabelItem> {
        new LabelItem() { Id = 0, CustomColor = System.Drawing.Color.Green, CustomCaption = "Green" },
        new LabelItem() { Id = 1, CustomColor = System.Drawing.Color.Red, CustomCaption = "Red" },
        new LabelItem() { Id = 2, CustomColor = System.Drawing.Color.Yellow, CustomCaption = "Yellow" }
    },
    AppointmentLabelMappings = new DxSchedulerAppointmentLabelMappings() {
        Id = "Id",
        Color = "CustomColor",
        Caption = "CustomCaption"
    },
    ....
};
```

> RecurrenceInfo syntax looks too complicated, in my opinion it should be either or object or separate fields.

This is the recurrence view's format in the database field. The same format is used in our components: ASPxScheduler, Bootsrap Scheduler, WinForms Scheduler. Thus, the current recurrence view is compatible with other "Scheduler" components, so it will be easier to migrate to DxScheduler for Blazor.

> It would be great to have resource column within each day, e.g. free rooms/cars e.t.c
> Is it possible to customize appearance of appointment items?

So far, there is no such possibility, but it will be implemented in the future.

**Comment by euroUK** [comment]
Thank you!

I will take a look to ASPxScheduler to understand how to geberate reccurence info correctly.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
