### ISSUE TITLE
Enhancement: Controls sizing

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#42]
Hi DevExpress team,

It would be great to have small/default/large sizing [like in bootstrap](https://getbootstrap.com/docs/4.3/components/input-group/#sizing). 

I tried adding "input-group-sm" to the DxComboBox but it doesn't look nice.

Thanks
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,
 
Thank you for the suggestion. I've added it to the backlog so that it will be considered in the future.
