### ISSUE TITLE
bug: DxDataGrid grouping header should show Caption instead of FieldName

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#43]
Hi DevExpress team,

today I implemented a grouped grid in one of my apps. It seems that grouping takes the wrong value for the caption. 
My column's definition:
```
<DxDataGridColumn Field="@nameof(MessageStoreActivity.RegionName)" Caption="Region" GroupIndex="0">
    <DisplayTemplate>
        @{
            var item = (MessageStoreActivity)context;
        }
        <div class="small align-middle">
            @item.RegionName
        </div>
    </DisplayTemplate>
</DxDataGridColumn>
```

However the Grid shows the Fieldname "RegionName" instead of Caption with value "Region" 

![image](https://user-images.githubusercontent.com/8734624/64529366-0005ec80-d30b-11e9-80fe-aa51d435fac5.png)

**Comment by outsidergiant** [comment]
Hi,
 
Thank you for pointing this out. I reproduced this problem and am working on it. 
 
Regards.

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,
 
Thanks for bringing our attention to this issue.
 
We will provide the fix in the next update.
 
Your patience is appreciated.

**Comment by sven5** [comment]
Thanks for your update  @SergeySeleznyov

**Comment by SergeySeleznyov** [comment]
Hi @sven5 ,
 
This issue is fixed in yesterday's components update (version 0.3.2).
Would you please check it and let us know whether you have any difficulty with it?
