### ISSUE TITLE
ClientSideWithPrerendering does not build

### ISSUE THREAD

**Issue by Roneri75** [DevExpress/Blazor#44]
Hade some problems in my test app and wanted to see if i got the same in the latest version of your demo app but I get this when building the Demo project ClientSideWithPrerendering with no changes made to it, just freshly cloned:
Source file 'C:\Users\...\source\repos\...\DevExpress\Blazor\demo\BlazorDemo.ClientSideWithPrerendering\BlazorDemo.ClientSide\obj\Debug\netstandard2.1\RazorDeclaration\Pages\CodeSnippets\Charts\CodeSnippet-Charts-MultiplePanesCustomization.razor.g.cs' could not be found.	BlazorDemo.ClientSide

**Comment by outsidergiant** [comment]
Hi,

I tried to reproduce this issue but was able to successfully build the project.
![BuildResult](https://user-images.githubusercontent.com/17219648/65305996-14f54200-db8d-11e9-8c20-e255a6a510f9.png)
Would you please clarify whether you have the latest [.NET Core Release Candidate 1](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-release-candidate-1/)?

**Comment by outsidergiant** [comment]
@Roneri75, I haven't heard from you for a while and since we were not able to reproduce the issue you are describing, I'll close this "issue" for now. Feel free to let us know if it appears again on your side or if you have any other questions related to our components.
