### ISSUE TITLE
Date Grid Column not working

### ISSUE THREAD

**Issue by m3awadhi** [DevExpress/Blazor#45]
Hello ,
DxDataGridDateEditColumn (Date) from  https://demos.devexpress.com/blazor/GridColumnTypes
is not updating when editing a record.

PackageReference Include="DevExpress.Blazor" Version="0.4.0"

**Comment by SergeySeleznyov** [comment]
Hello @m3awadhi,
 
I have reproduced it and will fix it ASAP.
 
Thank your for reporting this!

**Comment by SergeySeleznyov** [comment]
This issue has been fixed in the v0.4.1 NuGet package version we have just released.
 
Thank your for your patience!
