### ISSUE TITLE
Update Invoke to InvokeAsync (from Preview 8 --> RC1)s

### ISSUE THREAD

**Issue by donhuvy** [DevExpress/Blazor#46]
new code should to
```html
@code {
    bool IsDisabled = true;

    void OnTextChanged(string newValue)
    {
        if (!string.IsNullOrEmpty(newValue))
        {
            IsDisabled = false;
        }
        InvokeAsync(StateHasChanged);
    }
}
```

Please see https://stackoverflow.com/a/58055875/3728901

**Comment by donhuvy** [comment]
at here https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxTextBox#handle-a-text-change

**Comment by Nelda4** [comment]
Hello @donhuvy 

Thank you for pointing this out to us. 
It seems that we missed some old code snippets in the documentation. We've just corrected them. You can check this by following the [topic](https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxTextBox#handle-a-text-change) you mentioned.
 
Thank you for your time.
