### ISSUE TITLE
DataGrid not listing all records when    ShowPager="false"

### ISSUE THREAD

**Issue by m3awadhi** [DevExpress/Blazor#47]
Hello,
I noticed DataGrid is not listing all records when ShowPager="false" 
instead It displays only 10 records .
I think  expected behavior is  to display all records when Pager is disabled

Thanks

**Comment by outsidergiant** [comment]
Hi,

The grid shows data based on the [PageSize](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxDataGridBase-1.PageSize) property regardless of the pager's visibility. So, if you wish to show all the records at once, set **PageSize** to the maximum "Int32.MaxValue" value.
