### ISSUE TITLE
DataGrid - dynamic columns

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#49]
Spoiler, this is kind of a weird scenario.

I need to be able to add columns to a DataGrid dynamically. These custom columns are stored in my code as "Properties", and can be edited using a settings page by the user.
Here's a sample class of how this could be applied:
```
public class MyObject
{
	public string Name { get; set; } = "";

	public List<MyObjectProperty> Properties { get; set; } = new List<MyObjectProperty>();

}
public class MyObjectProperty
{
	public string Name { get; set; } = "";
	
	public string Value { get; set; } = "";
}
```

I can display these by grabbing the first one and getting all the properties by their name using the context.
```
foreach (var prop in data.First().Properties)
{
	<DxDataGridColumn Caption="@prop.Name">
		<DisplayTemplate>
			@{
				var myObj = (context as MyObject);

				var currentObj = myObj.Properties.FirstOrDefault(x => x.Name == prop.Name);

				<span>@currentObj.Value</span>
			}
		</DisplayTemplate>
	</DxDataGridColumn>
}
```

The problem lies in not being able to set the `Field` in the column. Without that, I cannot sort or filter these custom columns.
Is there a way to get this working? Maybe a lambda function with the context instead of the field name so I can get the exact object?

Thanks in advance!

**Comment by SergeySeleznyov** [comment]
Hi @GerritBergen ,
 
If you try to set `Field `to a column, DataGrid will try to get values from items of `Data`.
As the way you are using to get `Property` values is custom, DataGrid cannot get them.
 
I would recommend you change the data source to the collection of `IEnumerabe<ExpandoObject>`.
You can find an example here:
https://github.com/DevExpress-Examples/blazor-DxDataGrid-bind-to-DataTable
 
Would you please try it and let us know if it helps you?

**Comment by GerritBergen** [comment]
I will try this out asap and let you know :) Thanks!

**Comment by GerritBergen** [comment]
ExpandoObject worked a treat, thank you!
