### ISSUE TITLE
DataGrid - Save group/filter/sort

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#51]
Is it possible right now to save the layout of the DataGrid? Like calling a SaveLayout function and getting a class back that can be serialized and saved in LocalStorage?

**Comment by SergeySeleznyov** [comment]
Currently, DataGrid does not have this feature.
However, we have already received such requests, and this functionality will be on our To-Do list.
 
Thank you for pointing out to this.

**Comment by GerritBergen** [comment]
Ok sounds good. Do you know around when this might be available?

**Comment by SergeySeleznyov** [comment]
We are about to start writing the roadmap for the next half a year.
So, we have not defined the ETA for the next features. 

It looks like this feature doesn't relate to other functionalities and their implementation, so, if you say need it for production ASAP, we will try to increase the priority for this task.

**Comment by GerritBergen** [comment]
I definitely need this for a project I'm currently working on, but if it's not available soon, I'll just have to roll my own saving system.

PS: I'm really impressed by how fast you respond and helpful you guys are. So thumbs up!

**Comment by SergeySeleznyov** [comment]
Hi @GerritBergen,

We are planing to provide the DxDataGrid API that looks as follows:

```LayoutRestoring``` - the grid's event that fires when the grid is ready to load its previously saved "layout".
```LayoutChanged``` - the grid's event that fires when the grid "layout" is changed by a user; thus, the changed "layout" can be saved.

```string SetLayout()``` - the grid's method that saves the "layout" to a string (json).
```void SetLayout(string json)``` - the grid's method that loads the "layout" to a string (json).

The term "layout" denotes a set of DxDataGrid's visible parameters that can be changed by the end user:

* Grid's page index
* Column's visible index
* Column's group index
* Column's sort index
* Column's sort direction
* Column's filter


Would you please check this API and let us know whether it suits your project's requirement?
Thank your for your time and cooperation.

**Comment by GerritBergen** [comment]
This should work perfectly, thanks :)

**Comment by SergeySeleznyov** [comment]
Hi @GerritBergen,

We have [released the features you asked for](https://community.devexpress.com/blogs/aspnet/archive/2019/10/24/blazor-components-data-grid-layout-management-and-new-scroll-picker-mode-available-in-19-1-9.aspx).

You can find an [example illustrating how to use this feature](https://supportcenter.devexpress.com/ticket/details/t826240/blazor-data-grid-how-to-save-load-a-grid-s-layout-information).

Your feedback is highly appreciated.

**Comment by GerritBergen** [comment]
You guys are amazing. Thank you for all your hard work :)
