### ISSUE TITLE
Setting fore-/background-color of row depending on row item

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#53]
The elements I list in my DxDataGrid have a property ForeColor and BackgroundColor. I'd like to change the row color of each row depending on those properties. Is this possible?

**Comment by SergeySeleznyov** [comment]
Hi @rysep2,

Thank you for your question.
Currently DxDataGrid does not have this functionality.

I will add this task to our backlog. I think it might be something like the following [event in ASPxGridView](https://documentation.devexpress.com/AspNet/DevExpress.Web.ASPxGridView.HtmlRowPrepared.event)

Would it be enough for your task?

**Comment by rysep2** [comment]
Yes I think this would be enough for my task.

**Comment by SergeySeleznyov** [comment]
Hello,
 
In the latest 19.1.10 release, the Data Grid can decorate its elements depending on the data. [Here you can find a demo that explains this feature](https://demos.devexpress.com/blazor/GridHTMLDecoration).

Please feel free to reactivate this issue should you have any feedback or need assistance.

**Comment by rysep2** [comment]
This worked perfectly btw, thanks a lot!
