### ISSUE TITLE
DataGrid - Selection doesn't work if the grid is bound to IQueryable<T> and AutoMapper is used

### ISSUE THREAD

**Issue by bitdeploy** [DevExpress/Blazor#54]
Hi Guys,

I have a DxDataGrid bound to a IEnumerable<T> and using the SingleSelectedDataRowChanged event in order to get the selected item and within this event i set the SingleSelectedDataRow in order to display the row's selection (SelectionMode="DataGridSelectionMode.SingleSelectedDataRow").

When switching from IEnumerable<T> to IQueryable<t> the event still fires, but setting the SingleSelectedDataRow does not seem to have any effect, the grid's selection is not visible.

reagards,
Michael

**Comment by outsidergiant** [comment]
Hello Michael,

I tried to reproduce this issue but wasn't able to do so: a row is successfully selected. Would you please modify the attached project so I can reproduce this issue on my side? 

[BlazorProject.zip](https://github.com/DevExpress/Blazor/files/3724579/BlazorProject.zip)

**Comment by bitdeploy** [comment]
Hi Paul,

your sample works fine - I'll review my solution. The problem seems to be AutoMapper related, because binding to IQueryable<TModel> works while IQueryable<TDto> doesnt.

**Comment by outsidergiant** [comment]
Michael,

May I take a look at your model? I would like to analyze it thoroughly once I manage to replicate the problematic behavior on my side.

**Comment by bitdeploy** [comment]
Paul,

i'll try to modify your sample. What I've noticed is that the DXDataGrid bound to a IQueryable is requerying the database every time I change the selection.

<pre>
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*)
      FROM [Country] AS [c]

info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__p_0='10'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(@__p_0) [c].[Id], [c].[CreatedBy], [c].[CreatedOn], [c].[ModifiedBy], [c].[ModifiedOn], [c].[Name]
      FROM [Country] AS [c]
      ORDER BY [c].[Name], [c].[Id]

info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__p_0='10'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(@__p_0) [c].[Id], [c].[CreatedBy], [c].[CreatedOn], [c].[ModifiedBy], [c].[ModifiedOn], [c].[Name]
      FROM [Country] AS [c]
      ORDER BY [c].[Name], [c].[Id]
</pre>

Since I was using the AutoMapper's .ProjectTo method I may received new objects every time and the selectedObject mismatched. But this is just a wild guess...

regards,
Michael

**Comment by SergeySeleznyov** [comment]
Hi @rysep2,

Thank you for informing us of this issue.
I have attached the screencast of the misbehavior.

![ezgif-6-dde48c6dc9cf](https://user-images.githubusercontent.com/950357/66826907-41b33400-ef56-11e9-8887-df01163a9e17.gif)

Would you please check whether this issue is the same as you describe?

**Comment by bitdeploy** [comment]
as requested... 

[BlazorProject.zip](https://github.com/DevExpress/Blazor/files/3729151/BlazorProject.zip)

**Comment by outsidergiant** [comment]
Michael,

Thank you for modifying my project. We will research this case.

**Comment by Nelda4** [comment]
Hello Michael,

I'd like to inform you that the fix will be in the next release. 

Thank you for your patience!

**Comment by Nelda4** [comment]
Hello Michael,

The fix is published in the latest release 19.1.10. Please note that the [KeyFieldName](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxDataGridBase-1.KeyFieldName) property value should be specified for correct operation.

Please feel free to reopen this issue if you have any feedback or need assistance.
