### ISSUE TITLE
Is it possible to start scheduler's week with monday?

### ISSUE THREAD

**Issue by Lesterdor** [DevExpress/Blazor#56]
Hey,
the scheduler's week starts with sunday. Is there any way to change this behaviour? I would like to start a week from monday until sunday.

best regards
Lester

**Comment by SergeySeleznyov** [comment]
Hi @Lesterdor,

DxScheduler has the FirstDayOfWeek property.
You can read more about it in the [documentation](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxSchedulerBase.FirstDayOfWeek).

Here is an example showing how to set Monday as the first day of the week:

```razor
<DxScheduler ...
             FirstDayOfWeek="@DayOfWeek.Monday">
    ...
</DxScheduler>    

```

Please try this property in your project and let us know whether you have any difficulties.

**Comment by Lesterdor** [comment]
Hey @SergeySeleznyov,
thank you so much for your help. It works fine. I've looked only in the [Online Demos - DevExpress UI for Blazor](https://demos.devexpress.com/blazor/SchedulerViewTypes#Overview) and there are 4 related API members listed.

**Comment by SergeySeleznyov** [comment]
I'm happy to help you @Lesterdor.
Please feel free to contact us should you have any questions.
