### ISSUE TITLE
label for in combination with Data Editors doesn't work

### ISSUE THREAD

**Issue by Lesterdor** [DevExpress/Blazor#58]
Hey,
if you have a look on you documentation: [Form Validation - Custom Form](https://demos.devexpress.com/blazor/FormValidation#CustomForm) you can see that the 
`label for` and `DxDataEditor's ID ` are the same. But if you click on the label in the form above, you don't jump into the mapped input.

I've tested this part of your documentation with Firefox 69.0.3 (64 Bit) and Edge.

**Comment by SergeySeleznyov** [comment]
Hi @Lesterdor,

I have reproduced this issue.
Thank you for informing us about it.

**Comment by outsidergiant** [comment]
Hello @Lesterdor,

I'm happy to inform you that this issue has been fixed in the latest release 19.1.10.
[Here you can find a live demo](https://demos.devexpress.com/blazor/FormLayout#Overview) of how the Form Layout Caption clicks work now.
