### ISSUE TITLE
Demo Website CSS Issue (Mask-Image) on Edge

### ISSUE THREAD

**Issue by PackFan2019** [DevExpress/Blazor#60]
It looks like that Demo Website have CSS Issue (Mask-Image) on Edge browser.  Everything looks good in other browsers, such as Chrome or Firefox, but on Edge, Logo image or drill-down images on treeview cannot display correctly.  

It looks like that it might be related to CSS Mask-Image which Edge does not support very well. 

https://demos.devexpress.com/blazor/

is there any quick fix or quick workaround on this? Thank you. 

![CSS Issue (Mask-Image) in Edge](https://user-images.githubusercontent.com/56656217/66959021-22d4a080-f02f-11e9-85a7-55b6fbe4669b.png)

**Comment by SergeySeleznyov** [comment]
Hi @PackFan2019,

Thank you for informing us.
Currently I cannot reproduce this issue in the Edge browser:

![image](https://user-images.githubusercontent.com/950357/66989813-bd83bc80-f0cd-11e9-838b-5c167cc783cf.png)

Would you please create a similar screenshot?
(The Edge version is at the bottom of its settings.)

Do you use any compatibility mode?

The screenshot you sent looks more similar to the IE11 render:

![image](https://user-images.githubusercontent.com/950357/66989879-db512180-f0cd-11e9-8b79-480cde2da76e.png)


If you use IE11 (or Edge in compatibility mode with the same result), please refer to the following issue [Support for Internet Explorer 11](https://github.com/DevExpress/Blazor/issues/35).

**Comment by PackFan2019** [comment]
Thank you for the info.  

It looks like that our company still uses an old version of Edge (probably 2018 version, see screenshot below), which might not have correct Mask-Image CSS function.  Since Edge only updates with Window updates, we might have to wait company-wide windows update to push late Edge to end users. 

You could close this ticket. Thank you for your help. 

![Edge Version](https://user-images.githubusercontent.com/56656217/67027517-4c450900-f0cf-11e9-89d9-8878b7512e63.png)

**Comment by SergeySeleznyov** [comment]
I'm happy to hear that you have found a solution.

Please feel free to contact us if you have any questions.
