### ISSUE TITLE
Allow DxComboBox binding to ValueTuple and KeyValuePair

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#64]
Hi DevExpress Team,

it would be great to have a DxComboBox bound to an `IEnumerable<(string code, string Name)>` or even a `IEnumerable<KeyValuePair<string,string>>`.
In this way we could avoid writing simple ViewModel classes.

Thanks
Sven

**Comment by SergeySeleznyov** [comment]
Hi @sven5,
Thank you for an interesting idea. I've put it in our backlog.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
