### ISSUE TITLE
Data Editor contains Date component but no Time component

### ISSUE THREAD

**Issue by emysa341** [DevExpress/Blazor#67]
For my use case, I need a data editor component, which takes time as input just like that date component takes date as input. If time is combined with Date editor it would be perfect just like the date editor in [asp.net ajax controls](https://demos.devexpress.com/aspxeditorsdemos/DateTime/DateEditor.aspx)

**Comment by outsidergiant** [comment]
Hello Ammad,

Thank you for your interest in our Blazor components.
We find this feature useful, and it is already in our Backlog.
I see that you are familiar with ASP.NET WebForms controls. Do you have applications built with DevExpress?

What are your current plans for Blazor? Are you going to create a new Blazor application or migrate your existing one to it? Are there any other components or features required for your application?

We are going to publish a [roadmap survey](https://community.devexpress.com/tags/Blazor/default.aspx) soon. I would appreciate it if you take a look at it and take part in it once it is published.

**Comment by emysa341** [comment]
@outsidergiant No I just found out the control while looking for time editor. This will be out first app using blazor. Yes sure I will look through it once its published. Thanks.

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
