### ISSUE TITLE
Components have different styles from demos and documentation

### ISSUE THREAD

**Issue by thomasdewulf** [DevExpress/Blazor#68]
I'm playing around with Blazor and DevExpress but can't get the styles to look like in the documentation. Is there something not mentioned in the setup guide?

- Vanilla Blazor project
- Latest release of DevExpress.Blazor

Sample repo: https://github.com/thomasdewulf/devexpress-blazor-test

Result I'm getting:

![image](https://user-images.githubusercontent.com/10937597/68547153-7a6fed00-03de-11ea-9131-1b8ff9b170eb.png)

**Comment by outsidergiant** [comment]
Hello Thomas,

In our [demos](https://demos.devexpress.com/blazor/) and [documentation](https://docs.devexpress.com/Blazor/400725/blazor-components) we use the "Pulse" theme:
![image](https://user-images.githubusercontent.com/17219648/68583274-d180cb00-048d-11ea-90f3-f1437ce0e710.png)

So, if you wish to have the grid with the Pulse theme, you need to include [a corresponding CSS file](https://github.com/DevExpress/Blazor/tree/master/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/wwwroot/css/switcher-resources/themes/pulse) to your project.
