### ISSUE TITLE
Multiple Selected rows in Master Detail Grid doesn't work with StateHasChanged 

### ISSUE THREAD

**Issue by lKinderBueno** [DevExpress/Blazor#69]
I faced a bug in Master Detail Grid. 
When I select multiple Rows using Shift button and the @bind-MultipleSelectedDataRows contains a StateHasChanged, the grid selects much more rows then the ones I selected

**Comment by Nelda4** [comment]
Hello @lKinderBueno 

It seems that the problem you mentioned is similar to the issue described in the [Data Grid for Blazor - Master-Detail scenario - A detail grid's rows are selected incorrectly with the "Shift" key](https://supportcenter.devexpress.com/internal/ticket/details/T829403) bug report in our Support Center. Would you please watch the video attached to the report to check whether the behavior is equal to yours?  If it is so, please track the bug report to get a notification when we update it.

**Comment by lKinderBueno** [comment]
> Hello @lKinderBueno
> 
> It seems that the problem you mentioned is similar to the issue described in the [Data Grid for Blazor - Master-Detail scenario - A detail grid's rows are selected incorrectly with the "Shift" key](https://supportcenter.devexpress.com/internal/ticket/details/T829403) bug report in our Support Center. Would you please watch the video attached to the report to check whether the behavior is equal to yours? If it is so, please track the bug report to get a notification when we update it.

Yes, it is the same issue. Is there a possible ETA for this bug fix?

**Comment by Nelda4** [comment]
It is difficult to estimate it precisely now, but we will inform you as soon as the issue is fixed.

Thank you!
