### ISSUE TITLE
DxDataGrid Grouping Summaries

### ISSUE THREAD

**Issue by GerritBergen** [DevExpress/Blazor#72]
Is there a way to see the sum or count of all columns combined within a group?
![image](https://user-images.githubusercontent.com/29714139/69348511-4e593500-0c44-11ea-9102-c634079bfb29.png)
So for instance you could see the total amount under the "Earned" column

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen 

At this moment, our DxDataGrid doesn't support the group/total summary feature. We have this feature on our ToDo list.

**Comment by GerritBergen** [comment]
Any idea when it might be available?

**Comment by zabelin-vladimir** [comment]
@GerritBergen
This feature is not scheduled yet. We are in the process of prioritizing our tasks for the upcoming 2020 year. I added your vote for this feature. Please vote for other Blazor-related products/features you’d like us to ship in the first half of 2020 in the [Blazor - Roadmap 2020 (Half-Year) - Your Vote Counts](https://community.devexpress.com/blogs/aspnet/archive/2019/11/07/blazor-roadmap-2020-your-vote-counts.aspx) article.

**Comment by GerritBergen** [comment]
Could I get an update on this?

**Comment by zabelin-vladimir** [comment]
Hello @GerritBergen

We are working on this feature and plan to release it soon.
Best regards!

**Comment by GerritBergen** [comment]
Thanks @zabelin-vladimir appreciate it :)

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
