### ISSUE TITLE
DxTextBox and other DX Controls: support two way binding

### ISSUE THREAD

**Issue by HeinzErnst** [DevExpress/Blazor#73]
DxTextBox and other DX Controls: support two way binding as in non DX Blazor Controls
Instead of `@bind-Text` and `@oninput="updateXy"` support
```
@bind=Property
@bind-Value=Property
@bind-Value=Property @bind-Value:event="onevent"
```
This would avoid a lot of code.

**Comment by SergeySeleznyov** [comment]
Hi @HeinzErnst,

This component supports two-way binding. See the [DxTextBox demo](https://demos.devexpress.com/blazor/TextBox#Overview):

```
<DxTextBox @bind-Text="@TextValue"></DxTextBox>

@code {
    string TextValue;
}
```

Our other components support two-way binding for data providing properties.
Would you please clarify what you wish to achieve?

**Comment by lyquocnam** [comment]
i think it mean the control will update state to change the value ?

**Comment by zabelin-vladimir** [comment]
Hello @lyquocnam

This behavior is caused by the fact that the default \<input\> element automatically initiates the *StateHasChanged* method after changing this \<input\> element. Our DxTextBox doesn't initiate such a method to avoid unnecessary UI changes. If it's necessary, you can call the *StateHasChanged* method after changing the corresponding property:


```
<p>Text: @TextValue</p>
<DxTextBox @bind-Text="@TextValue"></DxTextBox>
<input @bind="TextValue" />

@code {
    protected string _TextValue { get; set; } = "Test";
    public string TextValue {
        get => _TextValue;
        set {
            _TextValue = value;
            StateHasChanged();
        }
    }
}
```

**Comment by zabelin-vladimir** [comment]
Hello @HeinzErnst

We implemented the [BindValueMode](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxTextBoxBase.BindValueMode) property with version [20.1.4](https://community.devexpress.com/blogs/aspnet/archive/2020/06/09/blazor-ui-components-official-release-with-new-controls-amp-features-and-blazor-reports-available-in-v20-1.aspx) of our components. Using this property you can specify how to update the editor text when it is bound to a property/field: when this editor loses focus or on input every symbol.
Please check this feature on your side and share your thoughts with me. Your feedback is really appreciated.
