### ISSUE TITLE
For Grid in VirtualScrolling Mode,  Closing the Edit form by X button triggers OnRowInserting

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#74]
As title.

Closing the Edit form by Cancel button does not trigger OnRowInserting which is expected.

**Comment by outsidergiant** [comment]
Hi,

Thank you for drawing our attention to this! This behavior is incorrect and we will work on it within the context of the [DataGrid for Blazor - The RowInserting and RowUpdating events are raised if the "Close" button is clicked in a popup edit form](https://www.devexpress.com/Support/Center/Question/Details/T837683/datagrid-for-blazor-the-rowinserting-and-rowupdating-events-are-raised-if-the-close) thread.
We will update it once we have any news.

**Comment by outsidergiant** [comment]
Hi,

We fixed this issue in v19.1.10 and this version is already released. So, try the fix and our new features and feel free to share your feedback with us and/or contact us if you have any questions.
