### ISSUE TITLE
Grid virtualscrollmode does not seem to work in master/detail setup.

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#75]
as title.

Also it seemed upper or left boundaries of the grid disappear when the grid contains rows with many columns in horizontal scroll mode.

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc,

I reproduced the following problem:
When the Master-Detail scenario is used and the VirtualScrolling mode is enabled in the master grid, its detail buttons are not shown:
![](https://user-images.githubusercontent.com/42369178/70316830-8f993980-182d-11ea-84b3-94810a190aee.png)

Did you mean this issue?
I created a public ticket in our Support Center:
[DataGrid for Blazor - Master-Detail scenario - The Detail buttons are not shown if the VirtualScrolling mode is enabled](https://www.devexpress.com/Support/Center/Question/Details/T838981/datagrid-for-blazor-master-detail-scenario-the-detail-buttons-are-not-shown-if-the)

> Also it seemed upper or left boundaries of the grid disappear when the grid contains rows with many columns in horizontal scroll mode.

I didn't reproduce this behavior. I tested it with 17 columns, a master-detail scenario, and the enabled horizontal scroll bar and virtual scrolling. The detail buttons are not shown, but all the borders seem to be displayed properly. I've attached my sample. Would you modify it to reproduce this issue?


[GHI75.zip](https://github.com/DevExpress/Blazor/files/3931836/GHI75.zip)

**Comment by SergeySeleznyov** [comment]
Hi @goldmannyc,

Happy to inform you that this issue is fixed in version [19.2.3](https://github.com/DevExpress/Blazor/releases/tag/v19.2.3).
Please feel free to reopen this issue should you have any difficulty.
