### ISSUE TITLE
Will Bootstrap styles be added automatically if a DevExpress Blazor component exists on a page?

### ISSUE THREAD

**Issue by outsidergiant** [DevExpress/Blazor#76]
Hi everyone! Can I use bootstrap layout for rows and cols as it follows from fact that  components use Bootstrap itself. Do I need to add bootstrap styles explicitly or if I add one visible control all css will be included automatically?

_Originally posted by @Sm1le291 in https://github.com/DevExpress/Blazor/issues/14#issuecomment-563253567_

**Comment by outsidergiant** [comment]
Hello @Sm1le291,

Our components use Bootstrap rendering but we do not distribute Bootstrap styles and stripts. So you need to include the corresponding stylesheet file manually. This also allows you to include any other theme rather than the Default one.

**Comment by Sm1le291** [comment]
@outsidergiant big thanks) I'll check it
