### ISSUE TITLE
Use DxTextBox as DxDataGridColumn.EditTemplate not captures the update made on DxTextBox

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#78]
To reproduce it,  you can add below column into the blazor server demo's page GridColumnTypes.razor,  users' update made in the textbox not captured in the event handler OnRowUpdating's parameter newValues.

`<DxDataGridColumn Field="@nameof(WeatherForecast.TemperatureC)">
        <EditTemplate>
            @{
                string str = ((CellEditContext)context)?.CellValue?.ToString();
                <DxTextBox @bind-Text="@str" />
            }
        </EditTemplate>
    </DxDataGridColumn>`

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc,

I recommend you check the [Data Grid - Templates](https://demos.devexpress.com/Blazor/GridTemplate) demo and take note of the ComboBox in the *EditTemplate* template of the "Availability" column. Use the same approach with the TextChanged event in your code as in the mentioned demo with the SelectedItemChanged event.

Feel free to re-open this issue if you have any further questions.
