### ISSUE TITLE
How set the theme for a new Blazor app?

### ISSUE THREAD

**Issue by noufionline** [DevExpress/Blazor#81]

**Comment by zabelin-vladimir** [comment]
Hello @noufionline

If you create an application with the Blazor App Microsoft template, the application will use the standard Bootstrap theme. This theme's stylesheet is located in the "wwwwroot/css/bootstrap" folder and is linked in the layout file's HEAD section:

* In the Pages/_Host.cshtml file for server-side Blazor.
* In the wwwroot/index.html file for client-side Blazor.


To use another theme, replace the link to the css/bootstrap/bootstrap.min.css file with a link to a CSS file of a DevExpress or external Bootstrap theme. For example, you can check the following [themes](https://github.com/DevExpress/Blazor/tree/master/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/wwwroot/css/switcher-resources/themes)[,](https://github.com/DevExpress/Blazor/tree/master/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/wwwroot/css/switcher-resources/themes)[ which are used in our demos](https://github.com/DevExpress/Blazor/tree/master/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/wwwroot/css/switcher-resources/themes).

We are currently working on a documentation article, which relates to this question. As soon as it's ready, I will publish a link to it here.

**Comment by zabelin-vladimir** [comment]
Hello,

I would like to note that we published the [Themes](https://docs.devexpress.com/Blazor/401523/common-concepts/themes) article in our documentation. Don't hesitate to share your thoughts about this topic!
