### ISSUE TITLE
Whether to support orgchart in the future?

### ISSUE THREAD

**Issue by qiang999** [DevExpress/Blazor#82]
Hello,I have a problem.
Whether to support orgchart in the future？

**Comment by zabelin-vladimir** [comment]
Hello @qiang999

You can check our plans and vote for specific controls\features in our [Blazor - Roadmap 2020 (Half-Year)](https://community.devexpress.com/blogs/aspnet/archive/2019/11/07/blazor-roadmap-2020-your-vote-counts.aspx).

Please describe the scenario where you want to use such a control in greater detail. Which type of data do you want to show using such a chart? Do you have any additional requirements (data editing, etc.)?

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
