### ISSUE TITLE
Demo is asking for DevExtreme.AspNet.Data not found

### ISSUE THREAD

**Issue by bdnts** [DevExpress/Blazor#83]
Just following the instructions to launch the demo locally, VS16.4.2, BlazorDemo.ServerSide, DevExpress.Blazor already installed (V19.1.10)
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package DevExtreme.AspNet.Data. No packages exist with this id in source(s): DevExpress Nuget, Microsoft Visual Studio Offline Packages	BlazorDemo.ServerSide	C:\Users\brian.douglass\Documents\Source\Downloads\DevExpressBlazor-master\Blazor-master\demo\BlazorDemo.ServerSide\BlazorDemo.ServerSide\BlazorDemo.ServerSide.csproj	1	

Not available with DevExpress Nuget Dev URL.  Do I have to get a trial license for this also?
If so, does this mean DevExpress Blazor also needs a DevExtreme license?

**Comment by bdnts** [comment]
Just created a vanilla Blazor project, tried adding DevExpress.Blazor, got an error that there is a dependency on DevExtreme.AspNet.Data.  

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package DevExtreme.AspNet.Data. No packages exist with this id in source(s): DevExpress Nuget, Microsoft Visual Studio Offline Packages	BlazorApp1	C:\Users\brian.douglass\Documents\Source\Downloads\DevExpress\BlazorApp1\BlazorApp1\BlazorApp1.csproj	1	

Disappointing.

**Comment by outsidergiant** [comment]
Hi,

Thank you for contacting us.
Though the DevExtreme.AspNet.Data package is used for data operations supported by our components, the DevExtreme license is not required to work with our Blazor components.

Would you please record a video showing the steps you performed to reproduce this issue? I also captured a video and attached it to this comment to show how it works on my side. The project from the video is also attached. I look forward to your response.
[BlazorApp1.zip](https://github.com/DevExpress/Blazor/files/4018217/BlazorApp1.zip)
[Video.zip](https://github.com/DevExpress/Blazor/files/4018220/Video.zip)

**Comment by bdnts** [comment]
Hi,
I've uploaded a video of the steps that generate the error.  This is for BlazorDemo.ServerSide.

[DevExpress Blazor.zip](https://github.com/DevExpress/Blazor/files/4018630/DevExpress.Blazor.zip)

I will do a video of the default blazor app next.

**Comment by bdnts** [comment]
Here is a video creating a default Blazor app and then adding DevExpress.Blazor.
[DevExpressBlazorDefault.zip](https://github.com/DevExpress/Blazor/files/4018685/DevExpressBlazorDefault.zip)

Thanks in advance for looking at these for me.
Cheers

**Comment by outsidergiant** [comment]
Thank you for providing these videos. It occurs because the standard nuget.org package source is not added to your Visual Studio:
![NuGetPackageOptions](https://user-images.githubusercontent.com/17219648/71726791-3d0d6600-2e49-11ea-9cc2-0bea6d3986a4.png)

To resolve the issue, add it using the following source: 
https://api.nuget.org/v3/index.json
![NuGetOrg](https://user-images.githubusercontent.com/17219648/71726928-aa20fb80-2e49-11ea-9d4f-3832a794f591.png)

We will update our Readme.md and documentation to prevent such errors in the future.

**Comment by bdnts** [comment]
Success!  Updating the nuget sources resolved the error for both the Demos and the default project.

I did run into a null reference exception when running the Forms Validation demo.  Also, there were warning notices about deprecated classes and methods.  When I have a moment, I'll file a ticket on those also.

Thanks again for the assistance.  Excellent.
