### ISSUE TITLE
Grid Layout Restoration Question

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#85]
We have a use case where we re-use the same grid on the page,  the columns and data will be re-populated based on the database table being selected. In this use case, the grid layout restoration event is not triggered (as expected since it is only triggered the first time the grid being loaded). Will you please suggest a solution to handle this scenario?

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc 

I need to reproduce this issue on my side to find its cause. Please provide me with a sample project illustrating the described scenario, so that I can check it locally. I look forward to your reply.

**Comment by goldmannyc** [comment]
Thanks for your response.

I added you to the sample project (https://github.com/goldmannyc/Blazor.git),  please use branch 19.1.0 for the scenario we discussed.  It is for the Server Side Blazor in the demo folder. 

Also interesting issue I found out,  Switching Items and Columns in the latest Devexpress blazor  project will throw exception.

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc

Thank you for sharing your sample project with me.
The cause of this behavior is that you use the same grid in this case and it's not updated. If you want to update your grid based on the *dataType* property, I recommend you set the [@key](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#use-key-to-control-the-preservation-of-elements-and-components) attribute to this property:
`<DxDataGrid @key="@dataType" Data="@list"`
Let me know if it helps.

> Also interesting issue I found out, Switching Items and Columns in the latest Devexpress blazor project will throw exception.

Would you please clarify which page from your project I should use to reproduce this issue? As far as I understand, you try to re-order columns and get the mentioned exception. I checked this behavior with our [online demo](https://demos.devexpress.com/Blazor/GridColumnTypes) and cannot reproduce that.

**Comment by goldmannyc** [comment]
Thanks for your suggestion.  

I will try adding the key to the grid and test.

As for the second question, my project is on 19.1.10 and it worked,   if I do the same on version 19.2.1 (Use same grid but changing the columns and data), it will throw exception. You can just copy/past the same page onto 19.2.1  and you will see the exception.

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc 

Thank you for your clarification. I recommend you use an approach with the *@key* attribute from my previous reply, it should help with this issue as well.

**Comment by goldmannyc** [comment]
Perfect, adding the @key attribute solves the issue.

Thanks again for the response.
