### ISSUE TITLE
DxPopup for Blazor: Dragging and fadein/out?

### ISSUE THREAD

**Issue by Phloog** [DevExpress/Blazor#88]
Is it planned for the blazor DxPopup to optionally be draggable (dragging its header), and to have it smoothly fade in/out (using css transitions or javascript)? If not, could this be added to the wish list? :)

**Comment by outsidergiant** [comment]
Hi,

Thank you for contacting us. Yes, we have these features in our plans. Let us know if your application requires other features that are not implemented in our components yet. See also the [Blazor UI - 2020 Roadmap
](https://community.devexpress.com/blogs/aspnet/archive/2020/01/29/devexpress-blazor-2020-roadmap.aspx)

**Comment by zabelin-vladimir** [comment]
Hello,
We're closing this issue because from now on we address technical requests only in our [Support Center](https://www.devexpress.com/ask). If you have any questions, ideas, wish to share feedback or report an issue, you are welcome to create a ticket in our Support Center.
 
Best regards,
Vova
