### ISSUE TITLE
Grid: allow popup windows for data edit in scrolling modes

### ISSUE THREAD

**Issue by goldmannyc** [DevExpress/Blazor#90]
Currently popup windows for data edit is only for Grid in Virtual Scrolling mode, Is there a way to enable this in other scrolling modes?

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc,

At the moment, DxDataGrid doesn't provide a special API to change the Edit Form type. This task in our ToDo list. Stay tuned to our updates.

Regards,
Vova

**Comment by goldmannyc** [comment]
Will you be able to provide an update on the potential delivery date on this feature?  We use the grid for a datasets with large number of columns, popup editing window is absolutely needed for us.

thx

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc

We don't plan to release this feature in our next update. We will discuss it while planning features for our future updates.

**Comment by goldmannyc** [comment]
Thanks for the update,  just wondering is there a way to enable horizontal scroll under virtual scrolling mode?  that may address our requirement for the moment we well.

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc 

Would you please clarify which exact issue you faced with these two features? I tested them locally and they work properly together. Please review my sample.

[GHI90.zip](https://github.com/DevExpress/Blazor/files/4451435/GHI90.zip)

**Comment by zabelin-vladimir** [comment]
Hello @goldmannyc 

I would like to note that recently [we released the v20.1.6 of our controls][0]. One of the released features is the [EditMode][1] property. You can set this property to the [DataGridEditMode.PopupEditForm][2] value, so Data Grid displays the edit form in a pop-up window. Please check the following demo illustrating different edit modes: [Data Grid - Edit Modes][3].

[0]: https://github.com/DevExpress/Blazor/releases/tag/20.1.6
[1]: https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxDataGrid-1.EditMode
[2]: https://docs.devexpress.com/Blazor/DevExpress.Blazor.DataGridEditMode
[3]: https://demos.devexpress.com/Blazor/GridEditData#EditModes
