### ISSUE TITLE
dxdatagrid paging navigation ui 

### ISSUE THREAD

**Issue by isvander** [DevExpress/Blazor#92]
dear dx team, got some minor ui issue for DxDataGrid for blazor after i updated dxblazor from 19.1.10 to 19.2.3, (also tried 19.2.4 preview with same result)

here screenshot with pagesize parameter enabled.

![image](https://user-images.githubusercontent.com/7314004/74895398-19d05300-53c4-11ea-8ded-d1d1dd744dad.png)

and here without pagesize param

![image](https://user-images.githubusercontent.com/7314004/74895561-85b2bb80-53c4-11ea-8ccf-2eee204b80a5.png)

thank you

**Comment by zabelin-vladimir** [comment]
Hello @isvander

We changed our client-side resource registration between the mentioned versions.
In the 19.2+ versions, it's necessary to link the following file to the HEAD section of your layout:

For a server-side Blazor, add the line below to the _Host.cshtml file:

```
<head>  
    ...  
    <link href="_content/DevExpress.Blazor/dx-blazor.css" rel="stylesheet" />  
</head> 
```

For a client-side Blazor, add the line below to the index.html file:

```
<head>  
    ...  
    <link href="_content/DevExpress.Blazor/dx-blazor.css" rel="stylesheet" />  
</head>  
```

**Comment by isvander** [comment]
Thank you that fixed it @zabelin-vladimir

**Comment by isvander** [comment]
@zabelin-vladimir 
actually i have some question about this version upgrading, is there any other change to be made in project beside adding new css? or is it already documented somewhere?
thank you

**Comment by zabelin-vladimir** [comment]
Hello @isvander

You can check the corresponding [releases](https://github.com/DevExpress/Blazor/releases) on GitHub and check the list of **Breaking Changes** in each release.
Also, you can check this list on the [Version History](https://supportcenter.devexpress.com/versionhistory?platformsWithProducts=3c616c71-03dc-46b9-a54f-1334a22dffe7&entries=BreakingChanges&startBuildName=19.1.10&endBuildName=19.2.4&buildsMode=Range&hasPlatformsWithProducts=true) page on our site.

**Comment by isvander** [comment]
thank you @zabelin-vladimir
