### ISSUE TITLE
Question: DxTreeView reload Data with persisting selection

### ISSUE THREAD

**Issue by sven5** [DevExpress/Blazor#93]
Hi Team!

I'm currently trying to accomplish the following scenario:

1. Load DxTreeView with data
2. Select a child node and edit its text and save to database
3. Reload the changed child node - or reload all from database
4. Select the child node again

In short, I'd like to have the treeview reflect the changes made to one node (e.g. text property).
Could you please advice how to do this?

Thanks
Sven

**Comment by sven5** [comment]
Ok,

I found the solution:

1. Reload items from database
2. Call `StateHasChanged`
3. Call `treeview.CollapseAll`
4. Call `treeview.ExpandToNode`
5. Call `treeview.SelectNode`

**Comment by guerxingGit** [comment]
I reloaded datas for treeview,and call StateHasChanged method,but it,s not changed

**Comment by guerxingGit** [comment]
Ok,
I found the solution:
1、renew data list
2、reloaded data for list
