### ISSUE TITLE
_Imports.razor doesn't recognize DevExpress

### ISSUE THREAD

**Issue by omgitzdave** [DevExpress/Blazor#95]
I've installed DevExpress Blazor from my NuGet feed and I've added the following line to _Imports.razor:

@using DevExpress

After recompiling the solution, I receive an error saying the namespace cannot be found.  I've tried rebuilding and reinstalled all NuGet packages with the Update-Package -reinstall command, but DevExpress is still missing. 

I'm on Visual Studio 2019 Preview.  Any ideas?

**Comment by outsidergiant** [comment]
Hi,

Thank you for contacting us.
You need to add the `@using DevExpress.Blazor` namespace as described in the [Register DevExpress Resources](https://docs.devexpress.com/Blazor/401057/getting-started/create-a-new-application#step-3---register-devexpress-resources) article. Let me know if you have additional questions.
