### ISSUE TITLE
Where can I get the code for the Web API services?

### ISSUE THREAD

**Issue by ypaez** [DevExpress/Blazor#96]
In this code you use web API services to get the data

DataGridWebApi/Orders
DataGridWebApi/CustomersLookup
DataGridWebApi/ShippersLookup

where can we get the code of this services to see the correct implementation to consume this services from grid control? Better if you have examples using SQL server and other data sources on the back end.

Thanks

**Comment by zabelin-vladimir** [comment]
Hello @ypaez

> Better if you have examples using SQL server and other data sources on the back end.

In this case, I recommend you review [this example](https://github.com/DevExpress-Examples/blazor-webassembly-dxdatagrid-export), where you can find the code of the Web API project, which returns the grid's data source. Check the *DataSourceWebApi* project and pay attention to the [Products controller](https://github.com/DevExpress-Examples/blazor-webassembly-dxdatagrid-export/blob/19.2.2%2B/CS/DataSourceWebApi/DataSourceWebApi/Controllers/ProductsController.cs)'s code.
