### ISSUE TITLE
DxPopup as a service

### ISSUE THREAD

**Issue by Blackleones** [DevExpress/Blazor#99]
Hi, 
I would like to ask if you are thinking about implementing a service through which we can show and close the popup, like [Blazored Modal](https://github.com/Blazored/Modal)

I think this could help us to maintain a readable code and avoid spreading ```<DxPopup> ... </DxPopup>``` in all pages that need a popup. Thanks to it, we could create multiple .razor files containing DxPopup (such as a specific popup template per file) and call each one by the service independently from who is the caller. 

Furthermore, we could avoid creating extra properties just for Popup's rendering-purpose like ```private bool _isVisible {get, set} = false;``` 

What do you think about it?

[Edit]
I've created an example project [example project](https://github.com/Blackleones/dxpopup_from_service) I've modified the Blazored Modal project so now it contains the minimum necessary for DxPopup. As you can see you can call a DxPopup programmatically and so, you can:

- create multiple DxPopup in multiple .razor files
- avoid creating properties like _isVisible

**Comment by zabelin-vladimir** [comment]
Hello @Blackleones

Thank you for your idea and your sample project.
We don't plan to implement such a service out of the box in our DxPopup component. This approach relates to the default Blazor approaches and can be implemented by each developer which uses our component with respect to their real scenario.
Also, I would like to note that a similar task can be implemented using the [Cascading values and parameters](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#cascading-values-and-parameters) approach (I attached a sample project illustrating that).
I suppose that we can [create an example](https://github.com/DevExpress/Blazor/blob/master/examples.md) to illustrate both approaches, so our other users can review it and add it to their application. What do you think about such an example?
[GHI99.zip](https://github.com/DevExpress/Blazor/files/4262497/GHI99.zip)

**Comment by Blackleones** [comment]
Your sample code is beautiful. I think it could be useful to have an example of it. Can you create an example pretty like the sample project extending it with a callback called when the user closes the popup?

**Comment by zabelin-vladimir** [comment]
Hello @Blackleones 

My apologies for the delayed reply. Would you please clarify your latest requirement in greater detail? As far as I understand, you want to handle some event which is implemented at the level of the *INotificationPopupOwner* and this event should fire after the *GlobalPopup* is closed. Am I right?

**Comment by Blackleones** [comment]
Hello @zabelin-vladimir 

You're right, I would fire an event after the GlobalPopup is closed. I think the best example could be a GlobalPopup with "ok" and "cancel" buttons. With that example you can show how to:

1.  implement a global popup
2. fire an event after the popup is closed
3. fire a specific event after the popup is closed. For example, a "Confirm" event will be fired when the user clicks on the "Ok" button, otherwise a "Cancel" event will fired. 

I think that we can implement point 3 in this way 
```csharp

private class CloseReason 
{
    public bool Ok = false;
    public bool Cancel = false;
    /* ... other props ... */
}

private void OnClose(CloseReason reason)
{
    if(reason.Ok)
        Confirm();
    if(reason.Cancel)
        Cancel();
}
```

**Comment by zabelin-vladimir** [comment]
Hello @Blackleones

It's possible to make the current component (the page from which you show the global popup) implement an interface with the corresponding handler and send that as a parameter to the *Show* method. I attached the modified sample to this post.

However, this approach has several limitations.

The current component should not be disposed of before its handler is fired to prevent a situation when the event of the nonexistent object is called. For example, it's possible if you call the popup from some component which is inside the *if (condition) *condition and this condition is changed to false while the global popup is closed. In this case, the component is disposed of, but the *OnOkClick* event of this component is called after you click the *Ok* button.

Another limitation is the fact that with this implementation only one global popup can be shown and it's not possible to implement the "toast notification" scenario when several of the same popups are shown.
[GHI99.zip](https://github.com/DevExpress/Blazor/files/4288442/GHI99.zip)
